package http

import (
	"strconv"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/grapestree/fgrapery/grapery/internal/domain"
	"go.uber.org/zap"
)

type characterRefPayload struct {
	CharacterID string `json:"characterId" binding:"required"`
	Role        string `json:"role"`
	Order       *int   `json:"order"`
	Notes       string `json:"notes"`
}

type sceneRefPayload struct {
	StorySceneID   string `json:"storySceneId" binding:"required"`
	Sequence       *int   `json:"sequence"`
	IsPrimaryScene bool   `json:"isPrimaryScene"`
}

// CreateStoryboard 创建 storyboard
func (h *Handler) CreateStoryboard(c *gin.Context) {
	userID, _ := c.Get("userID")

	var req struct {
		StoryID       string                `json:"storyId" binding:"required"`
		ParentID      *string               `json:"parentId"`
		Title         string                `json:"title" binding:"required"`
		RawInput      string                `json:"rawInput" binding:"required"`
		Content       string                `json:"content"`
		IsStandalone  bool                  `json:"isStandalone"` // Independent plot, AI won't reference parent context
		SceneCount    int                   `json:"sceneCount"`   // Requested number of scenes to generate (2-5, default 3)
		SceneRefs     []sceneRefPayload     `json:"sceneRefs"`    // References to story-level scenes (static locations)
		CharacterRefs []characterRefPayload `json:"characterRefs"`
		Tags          []string              `json:"tags" binding:"omitempty,max=3,dive,min=1,max=50"` // 最多3个标签，每个标签1-50字符
	}

	if err := c.ShouldBindJSON(&req); err != nil {
		InvalidParams(c, err.Error())
		return
	}

	h.logger.Info("CreateStoryboard called",
		zap.String("storyId", req.StoryID),
		zap.String("title", req.Title),
		zap.String("userId", userID.(string)))

	// Default scene count to 3 if not specified or out of range
	sceneCount := req.SceneCount
	if sceneCount < 2 || sceneCount > 16 {
		sceneCount = 6
	}

	storyboard := &domain.Storyboard{
		StoryID:      req.StoryID,
		ParentID:     "",
		CreatorID:    userID.(string),
		Title:        req.Title,
		RawInput:     req.RawInput,
		Content:      req.Content,
		IsStandalone: req.IsStandalone,
		SceneCount:   sceneCount,
		// StoryboardScenes are generated by AI, not passed in request
	}
	if req.ParentID != nil {
		storyboard.ParentID = *req.ParentID
	}

	if len(req.CharacterRefs) > 0 {
		storyboard.CharacterRefs = make([]domain.StoryboardCharacterRef, len(req.CharacterRefs))
		for i, ref := range req.CharacterRefs {
			order := i
			if ref.Order != nil {
				order = *ref.Order
			}
			storyboard.CharacterRefs[i] = domain.StoryboardCharacterRef{
				CharacterID: ref.CharacterID,
				Role:        ref.Role,
				Order:       order,
				Notes:       ref.Notes,
			}
		}
	}

	if len(req.SceneRefs) > 0 {
		storyboard.SceneRefs = make([]domain.StoryboardSceneRef, len(req.SceneRefs))
		for i, ref := range req.SceneRefs {
			seq := i
			if ref.Sequence != nil {
				seq = *ref.Sequence
			}
			storyboard.SceneRefs[i] = domain.StoryboardSceneRef{
				StorySceneID:   ref.StorySceneID,
				Sequence:       seq,
				IsPrimaryScene: ref.IsPrimaryScene,
			}
		}
	}

	// AI generation is handled by CreateStoryboard service when content is empty and rawInput is provided
	if err := h.svc.CreateStoryboard(c.Request.Context(), storyboard); err != nil {
		h.logger.Error("CreateStoryboard failed",
			zap.String("storyId", req.StoryID),
			zap.Error(err))
		InternalError(c, err.Error())
		return
	}

	// 添加标签（如果有）- 故事板标签添加到对应的故事上
	if len(req.Tags) > 0 {
		// 去重并规范化标签
		uniqueTags := make(map[string]bool)
		normalizedTags := make([]string, 0, len(req.Tags))
		for _, tag := range req.Tags {
			normalized := strings.TrimSpace(strings.ToLower(tag))
			if normalized != "" && !uniqueTags[normalized] {
				uniqueTags[normalized] = true
				normalizedTags = append(normalizedTags, normalized)
			}
		}
		if len(normalizedTags) > 0 {
			if err := h.svc.AddStoryTags(c.Request.Context(), storyboard.StoryID, normalizedTags); err != nil {
				h.logger.Warn("failed to add tags to story for storyboard",
					zap.String("storyboardId", storyboard.ID),
					zap.String("storyId", storyboard.StoryID),
					zap.Strings("tags", normalizedTags),
					zap.Error(err))
				// 不返回错误，标签添加失败不影响故事板创建
			}
		}
	}

	h.logger.Info("CreateStoryboard success",
		zap.String("storyboardId", storyboard.ID),
		zap.String("storyId", storyboard.StoryID),
		zap.String("parentId", storyboard.ParentID),
		zap.String("workflowStatus", storyboard.WorkflowStatus))

	Success(c, storyboard)
}

// GetStoryboard 获取 storyboard 详情
func (h *Handler) GetStoryboard(c *gin.Context) {
	id := c.Param("id")

	storyboard, err := h.svc.GetStoryboard(c.Request.Context(), id)
	if err != nil {
		if err == domain.ErrNotFound {
			NotFound(c, "storyboard not found")
			return
		}
		InternalError(c, err.Error())
		return
	}

	Success(c, storyboard)
}

// UpdateStoryboard 更新 storyboard
func (h *Handler) UpdateStoryboard(c *gin.Context) {
	userID, _ := c.Get("userID")
	id := c.Param("id")

	var req struct {
		Title         string                `json:"title"`
		Content       string                `json:"content"`
		RawInput      string                `json:"rawInput"`
		SceneRefs     []sceneRefPayload     `json:"sceneRefs"` // References to story-level scenes
		CharacterRefs []characterRefPayload `json:"characterRefs"`
	}

	if err := c.ShouldBindJSON(&req); err != nil {
		InvalidParams(c, err.Error())
		return
	}

	storyboard := &domain.Storyboard{
		ID:       id,
		Title:    req.Title,
		Content:  req.Content,
		RawInput: req.RawInput,
		// StoryboardScenes are managed separately via AI generation
	}

	if req.CharacterRefs != nil {
		storyboard.CharacterRefs = make([]domain.StoryboardCharacterRef, len(req.CharacterRefs))
		for i, ref := range req.CharacterRefs {
			order := i
			if ref.Order != nil {
				order = *ref.Order
			}
			storyboard.CharacterRefs[i] = domain.StoryboardCharacterRef{
				CharacterID: ref.CharacterID,
				Role:        ref.Role,
				Order:       order,
				Notes:       ref.Notes,
			}
		}
	}

	if req.SceneRefs != nil {
		storyboard.SceneRefs = make([]domain.StoryboardSceneRef, len(req.SceneRefs))
		for i, ref := range req.SceneRefs {
			seq := i
			if ref.Sequence != nil {
				seq = *ref.Sequence
			}
			storyboard.SceneRefs[i] = domain.StoryboardSceneRef{
				StorySceneID:   ref.StorySceneID,
				Sequence:       seq,
				IsPrimaryScene: ref.IsPrimaryScene,
			}
		}
	}

	if err := h.svc.UpdateStoryboard(c.Request.Context(), storyboard, userID.(string)); err != nil {
		InternalError(c, err.Error())
		return
	}

	Success(c, gin.H{"message": "storyboard updated successfully"})
}

// DeleteStoryboard 删除 storyboard
func (h *Handler) DeleteStoryboard(c *gin.Context) {
	userID, _ := c.Get("userID")
	id := c.Param("id")

	if err := h.svc.DeleteStoryboard(c.Request.Context(), id, userID.(string)); err != nil {
		InternalError(c, err.Error())
		return
	}

	Success(c, gin.H{"message": "storyboard deleted successfully"})
}

// GetStoryboardFeed 获取社区故事板 feed 流
// Query params:
//   - limit: 分页限制（默认20）
//   - offset: 分页偏移（默认0）
func (h *Handler) GetStoryboardFeed(c *gin.Context) {
	limit, _ := strconv.Atoi(c.DefaultQuery("limit", "20"))
	offset, _ := strconv.Atoi(c.DefaultQuery("offset", "0"))

	h.logger.Info("GetStoryboardFeed called",
		zap.Int("limit", limit),
		zap.Int("offset", offset))

	storyboards, total, err := h.svc.GetStoryboardFeed(c.Request.Context(), limit, offset)
	if err != nil {
		h.logger.Error("GetStoryboardFeed failed", zap.Error(err))
		InternalError(c, err.Error())
		return
	}

	h.logger.Info("GetStoryboardFeed result",
		zap.Int("count", len(storyboards)),
		zap.Int64("total", total))

	Success(c, gin.H{
		"storyboards": storyboards,
		"total":       total,
		"limit":       limit,
		"offset":      offset,
	})
}

// ListStoryboards 获取故事的 storyboards 列表
// Query params:
//   - storyId: 故事ID（必填）
//   - parentId: 父级ID（可选）- 为空或 "root" 时获取根故事板，指定ID时获取该父级的子故事板
//   - limit: 分页限制（默认20）
//   - offset: 分页偏移（默认0）
func (h *Handler) ListStoryboards(c *gin.Context) {
	storyID := c.Query("storyId")
	if storyID == "" {
		InvalidParams(c, "storyId is required")
		return
	}

	parentID := c.Query("parentId")
	limit, _ := strconv.Atoi(c.DefaultQuery("limit", "20"))
	offset, _ := strconv.Atoi(c.DefaultQuery("offset", "0"))

	h.logger.Info("ListStoryboards called",
		zap.String("storyId", storyID),
		zap.String("parentId", parentID),
		zap.Int("limit", limit),
		zap.Int("offset", offset))

	var storyboards []*domain.Storyboard
	var err error

	// 根据 parentId 参数决定获取哪些故事板
	switch parentID {
	case "", "root":
		// 获取根故事板（ParentID 为空或 "__root__"）
		storyboards, err = h.svc.ListRootStoryboards(c.Request.Context(), storyID, limit, offset)
	default:
		// 获取指定父级的子故事板
		storyboards, err = h.svc.ListStoryboardsByParent(c.Request.Context(), storyID, parentID, limit, offset)
	}

	if err != nil {
		h.logger.Error("ListStoryboards failed",
			zap.String("storyId", storyID),
			zap.Error(err))
		InternalError(c, err.Error())
		return
	}

	// Log details of each storyboard for debugging
	for _, sb := range storyboards {
		h.logger.Info("Storyboard found",
			zap.String("storyboardId", sb.ID),
			zap.String("storyId", sb.StoryID),
			zap.String("parentId", sb.ParentID),
			zap.String("workflowStatus", sb.WorkflowStatus),
			zap.String("title", sb.Title))
	}

	h.logger.Info("ListStoryboards result",
		zap.String("storyId", storyID),
		zap.Int("count", len(storyboards)))

	Success(c, gin.H{
		"storyboards": storyboards,
		"total":       len(storyboards),
		"limit":       limit,
		"offset":      offset,
	})
}

// GetStoryboardChildren 获取子 storyboards
func (h *Handler) GetStoryboardChildren(c *gin.Context) {
	parentID := c.Param("id")

	children, err := h.svc.GetStoryboardChildren(c.Request.Context(), parentID)
	if err != nil {
		InternalError(c, err.Error())
		return
	}

	Success(c, gin.H{
		"children": children,
		"count":    len(children),
	})
}

// GetStoryboardTree 获取完整的 storyboard 树
func (h *Handler) GetStoryboardTree(c *gin.Context) {
	rootID := c.Param("id")

	tree, err := h.svc.GetStoryboardTree(c.Request.Context(), rootID)
	if err != nil {
		InternalError(c, err.Error())
		return
	}

	Success(c, gin.H{
		"tree":  tree,
		"count": len(tree),
	})
}

// ForkStoryboard Fork 一个 storyboard
func (h *Handler) ForkStoryboard(c *gin.Context) {
	userID, _ := c.Get("userID")
	parentID := c.Param("id")

	var req struct {
		Title         string                `json:"title" binding:"required"`
		RawInput      string                `json:"rawInput" binding:"required"`
		Content       string                `json:"content"`
		IsStandalone  bool                  `json:"isStandalone"` // Independent plot, AI won't reference parent context
		SceneCount    int                   `json:"sceneCount"`   // Requested number of scenes to generate (2-5, default 3)
		SceneRefs     []sceneRefPayload     `json:"sceneRefs"`    // References to story-level scenes
		CharacterRefs []characterRefPayload `json:"characterRefs"`
	}

	if err := c.ShouldBindJSON(&req); err != nil {
		InvalidParams(c, err.Error())
		return
	}

	// Default scene count to 3 if not specified or out of range
	sceneCount := req.SceneCount
	if sceneCount < 2 || sceneCount > 5 {
		sceneCount = 3
	}

	newStoryboard := &domain.Storyboard{
		Title:        req.Title,
		RawInput:     req.RawInput,
		Content:      req.Content,
		IsStandalone: req.IsStandalone,
		SceneCount:   sceneCount,
		// StoryboardScenes are generated by AI, not passed in fork request
	}

	if len(req.CharacterRefs) > 0 {
		newStoryboard.CharacterRefs = make([]domain.StoryboardCharacterRef, len(req.CharacterRefs))
		for i, ref := range req.CharacterRefs {
			order := i
			if ref.Order != nil {
				order = *ref.Order
			}
			newStoryboard.CharacterRefs[i] = domain.StoryboardCharacterRef{
				CharacterID: ref.CharacterID,
				Role:        ref.Role,
				Order:       order,
				Notes:       ref.Notes,
			}
		}
	}

	if len(req.SceneRefs) > 0 {
		newStoryboard.SceneRefs = make([]domain.StoryboardSceneRef, len(req.SceneRefs))
		for i, ref := range req.SceneRefs {
			seq := i
			if ref.Sequence != nil {
				seq = *ref.Sequence
			}
			newStoryboard.SceneRefs[i] = domain.StoryboardSceneRef{
				StorySceneID:   ref.StorySceneID,
				Sequence:       seq,
				IsPrimaryScene: ref.IsPrimaryScene,
			}
		}
	}

	// AI generation is handled by ForkStoryboard service when content is empty and rawInput is provided
	if err := h.svc.ForkStoryboard(c.Request.Context(), parentID, userID.(string), newStoryboard); err != nil {
		InternalError(c, err.Error())
		return
	}

	Success(c, newStoryboard)
}

// LikeStoryboard 点赞 storyboard
func (h *Handler) LikeStoryboard(c *gin.Context) {
	userID, _ := c.Get("userID")
	id := c.Param("id")

	if err := h.svc.LikeStoryboard(c.Request.Context(), userID.(string), id); err != nil {
		InternalError(c, err.Error())
		return
	}

	Success(c, gin.H{"message": "storyboard liked successfully"})
}

// UnlikeStoryboard 取消点赞 storyboard
func (h *Handler) UnlikeStoryboard(c *gin.Context) {
	userID, _ := c.Get("userID")
	id := c.Param("id")

	if err := h.svc.UnlikeStoryboard(c.Request.Context(), userID.(string), id); err != nil {
		InternalError(c, err.Error())
		return
	}

	Success(c, gin.H{"message": "storyboard unliked successfully"})
}
