version: '3.8'

services:
  # 主应用服务
  grapes:
    image: your-registry/grapery-app:${TAG}   # 镜像名和tag由CI/CD注入
    container_name: grapery-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped