version: '3.8'

services:
  # 主应用服务
  grapes:
    image: crpi-kz6w8hb0pa94yvgy.cn-hangzhou.personal.cr.aliyuncs.com/grapery-dev/grapery-app:latest
    container_name: grapery-app
    ports:
      - "8080:8080"
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    command: ["./grapes-app", "--config", "/app/config.json"]
    restart: unless-stopped

  # llmchat 服务
  grapes-llmchat:
    image: crpi-kz6w8hb0pa94yvgy.cn-hangzhou.personal.cr.aliyuncs.com/grapery-dev/grapes-llmchat:latest
    container_name: grapes-llmchat
    ports:
      - "8081:8081"  # 如有需要可调整
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    command: ["./grapes-llmchat", "--config", "/app/config.json"]
    restart: unless-stopped
