#!/bin/bash

# Grapery 环境变量生成脚本
# 此脚本用于在CI/CD过程中生成.env文件

set -e

echo "🔧 开始生成 .env 文件..."

# 创建 .env 文件
cat > .env << EOF
# Grapery 环境配置文件
# 自动生成于 $(date)

# 数据库配置
DB_HOST=${DB_ADDR:-mysql}
DB_PORT=3306
DB_USER=${DB_USER:-grapery}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME:-grapery}

# Redis配置
REDIS_HOST=${REDIS_SERVER:-redis}
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# 应用配置
ENV=${DEPLOY_ENV:-production}
APP_PORT=8080
LLMCHAT_PORT=8070

# JWT配置
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRE_HOURS=24

# 支付配置
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

ALIPAY_APP_ID=${ALIPAY_APP_ID}
ALIPAY_PRIVATE_KEY=${ALIPAY_PRIVATE_KEY}
ALIPAY_PUBLIC_KEY=${ALIPAY_PUBLIC_KEY}
ALIPAY_NOTIFY_URL=${ALIPAY_NOTIFY_URL}
ALIPAY_RETURN_URL=${ALIPAY_RETURN_URL}

# 阿里云配置
ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
ALIYUN_REGION=${ALIYUN_REGION}
ALIYUN_OSS_BUCKET=${ALIYUN_OSS_BUCKET}
ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
ALIYUN_ROLE_ARN=${ALIYUN_ROLE_ARN}
ALIYUN_API_KEY=${ALIYUN_API_KEY}
ALIYUN_SECRET_KEY=${ALIYUN_SECRET_KEY}

# Coze配置
COZE_API_KEY=${COZE_API_KEY}
COZE_WORKSPACE_ID=${COZE_WORKSPACE_ID}

# 智谱AI配置
DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
DOUBAO_API_KEY=${DOUBAO_API_KEY}

# 邮件配置
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USERNAME=${SMTP_USERNAME}
SMTP_PASSWORD=${SMTP_PASSWORD}

# 日志配置
LOG_LEVEL=info
LOG_FILE=/var/log/grapery/app.log

# 缓存配置
CACHE_TTL=3600

# 安全配置
CORS_ALLOWED_ORIGINS=https://${DOMAIN_NAME}
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=60

# 监控配置
METRICS_ENABLED=true
METRICS_PORT=9090
EOF

echo "✅ .env 文件生成完成！"
echo "📋 文件内容预览："
echo "=================="
head -20 .env
echo "..."
echo "==================" 
