#!/bin/bash
# 自动生成 .env 文件脚本
# 用法：bash generate_env.sh
cat > .env <<EOF
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=${REDIS_PASSWORD}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRE_HOURS=${JWT_EXPIRE_HOURS}
ALIPAY_APP_ID=${ALIPAY_APP_ID}
ALIPAY_NOTIFY_URL=${ALIPAY_NOTIFY_URL}
ALIPAY_PRIVATE_KEY=${ALIPAY_PRIVATE_KEY}
ALIPAY_PUBLIC_KEY=${ALIPAY_PUBLIC_KEY}
ALIPAY_RETURN_URL=${ALIPAY_RETURN_URL}
ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
ALIYUN_OSS_BUCKET=${ALIYUN_OSS_BUCKET}
ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
ALIYUN_REGION=${ALIYUN_REGION}
COZE_API_KEY=${COZE_API_KEY}
COZE_WORKSPACE_ID=${COZE_WORKSPACE_ID}
DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}
DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
DOMAIN_NAME=${DOMAIN_NAME}
SERVER_HOST=${SERVER_HOST}
SERVER_PORT=${SERVER_PORT}
SMTP_HOST=${SMTP_HOST}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_PORT=${SMTP_PORT}
SMTP_USERNAME=${SMTP_USERNAME}
SSL_EMAIL=${SSL_EMAIL}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
EOF

echo ".env 文件已生成。" 
