#!/bin/bash

# Grapery 环境变量生成脚本
# 此脚本用于在CI/CD过程中生成.env文件

set -e

echo "🔧 开始生成 .env 文件..."

# 创建 .env 文件
cat > .env << EOF
# Grapery 环境配置文件
# 自动生成于 $(date)

DB_NAME=${DB_NAME}
DB_PASSWORD=${DB_PASSWORD}
DB_USER=${DB_USER}
DB_ADDR=${DB_ADDR}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_SERVER=${REDIS_SERVER}
JWT_SECRET=${JWT_SECRET}
ALIPAY_APP_ID=${ALIPAY_APP_ID}
ALIPAY_NOTIFY_URL=${ALIPAY_NOTIFY_URL}
ALIPAY_PRIVATE_KEY=${ALIPAY_PRIVATE_KEY}
ALIPAY_PUBLIC_KEY=${ALIPAY_PUBLIC_KEY}
ALIPAY_RETURN_URL=${ALIPAY_RETURN_URL}
ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
ALIYUN_OSS_BUCKET=${ALIYUN_OSS_BUCKET}
ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
ALIYUN_REGION=${ALIYUN_REGION}
ALIYUN_ROLE_ARN=${ALIYUN_ROLE_ARN}
ALIYUN_API_KEY=${ALIYUN_API_KEY}
ALIYUN_SECRET_KEY=${ALIYUN_SECRET_KEY}
COZE_API_KEY=${COZE_API_KEY}
COZE_WORKSPACE_ID=${COZE_WORKSPACE_ID}
DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}
DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
DOMAIN_NAME=${DOMAIN_NAME}
SERVER_HOST=${SERVER_HOST}
SERVER_PORT=${SERVER_PORT}
SMTP_HOST=${SMTP_HOST}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_PORT=${SMTP_PORT}
SMTP_USERNAME=${SMTP_USERNAME}
SSL_EMAIL=${SSL_EMAIL}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
DEPLOY_ENV=${DEPLOY_ENV}
DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
DOUBAO_API_KEY=${DOUBAO_API_KEY}

APP_PORT=8080
LLMCHAT_PORT=8070

# 日志配置
LOG_LEVEL=info
LOG_FILE=/var/log/grapery/app.log

# 缓存配置
CACHE_TTL=3600

# 安全配置
CORS_ALLOWED_ORIGINS=https://rankquantity.xyz
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=60

# 监控配置
METRICS_ENABLED=true
METRICS_PORT=9090
EOF

echo "✅ .env 文件生成完成！"
echo "📋 文件内容预览："
echo "=================="
head -20 .env
echo "..."
echo "==================" 
