// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/grapery/grapery/pb/service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e87e980cfa60e8, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Pong struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e87e980cfa60e8, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*Ping)(nil), "grapery.api.Ping")
	proto.RegisterType((*Pong)(nil), "grapery.api.Pong")
}

func init() {
	proto.RegisterFile("github.com/grapery/grapery/pb/service.proto", fileDescriptor_88e87e980cfa60e8)
}

var fileDescriptor_88e87e980cfa60e8 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0x59, 0x39, 0xee, 0x34, 0x36, 0x5e, 0x44, 0x90, 0x55, 0x50, 0xb6, 0x10, 0x51, 0x2f,
	0xb9, 0x3b, 0x3b, 0x0b, 0x41, 0x1b, 0x2b, 0x41, 0xac, 0xc4, 0x2e, 0xbb, 0xc4, 0x31, 0xe0, 0xce,
	0x0c, 0xd9, 0xdc, 0xaa, 0xad, 0x8f, 0xa0, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0xb2, 0xb9, 0x20, 0x8b,
	0x82, 0xd5, 0x24, 0xf3, 0xfd, 0xf9, 0xc9, 0xff, 0x8b, 0x63, 0x70, 0xe1, 0x71, 0x51, 0xaa, 0x8a,
	0x6a, 0x0d, 0xde, 0xb0, 0xf5, 0xaf, 0x3f, 0x93, 0x4b, 0xdd, 0x58, 0xdf, 0xba, 0xca, 0x2a, 0xf6,
	0x14, 0x48, 0xae, 0x27, 0xa2, 0x0c, 0xbb, 0x7c, 0x17, 0x88, 0xe0, 0xc9, 0x6a, 0xc3, 0x4e, 0x1b,
	0x44, 0x0a, 0x26, 0x38, 0xc2, 0x66, 0x29, 0xcd, 0xf7, 0x12, 0x8d, 0xb7, 0x72, 0xf1, 0xa0, 0x83,
	0xab, 0x6d, 0x13, 0x4c, 0xcd, 0x49, 0x70, 0x12, 0x47, 0x35, 0x01, 0x8b, 0x93, 0xe6, 0xd9, 0x00,
	0x58, 0xaf, 0x89, 0xa3, 0xc5, 0x5f, 0xbb, 0x22, 0x17, 0x83, 0x1b, 0x87, 0x20, 0xa5, 0x18, 0xb0,
	0x43, 0xd8, 0xce, 0xf6, 0xb3, 0xc3, 0xb5, 0xdb, 0x78, 0x8e, 0x8c, 0x12, 0xa3, 0x1e, 0x23, 0x84,
	0xf9, 0x9d, 0x18, 0x5d, 0x2d, 0xff, 0x2c, 0xaf, 0xc5, 0x6a, 0x67, 0x11, 0xa5, 0x63, 0xd5, 0x4b,
	0xa2, 0xba, 0x75, 0xfe, 0x6b, 0x45, 0x08, 0xc5, 0xce, 0xdb, 0xe7, 0xd7, 0xc7, 0xca, 0x56, 0xb1,
	0xa1, 0xdb, 0x99, 0xb6, 0x2f, 0xa6, 0xe6, 0x2e, 0x90, 0x43, 0x38, 0xcb, 0x8e, 0x2e, 0xcf, 0xdf,
	0x2f, 0x36, 0xe5, 0x58, 0x8c, 0xd2, 0xab, 0xf9, 0xb0, 0x9d, 0xaa, 0x99, 0x9a, 0xde, 0x1f, 0xfc,
	0x53, 0x68, 0x57, 0x55, 0x6a, 0xb4, 0x1c, 0xc6, 0x60, 0xa7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xcf, 0x09, 0xdb, 0xbe, 0x81, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GraperyClient is the client API for Grapery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GraperyClient interface {
	PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type graperyClient struct {
	cc *grpc.ClientConn
}

func NewGraperyClient(cc *grpc.ClientConn) GraperyClient {
	return &graperyClient{cc}
}

func (c *graperyClient) PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/grapery.api.Grapery/PingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraperyServer is the server API for Grapery service.
type GraperyServer interface {
	PingPong(context.Context, *Ping) (*Pong, error)
}

// UnimplementedGraperyServer can be embedded to have forward compatible implementations.
type UnimplementedGraperyServer struct {
}

func (*UnimplementedGraperyServer) PingPong(ctx context.Context, req *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}

func RegisterGraperyServer(s *grpc.Server, srv GraperyServer) {
	s.RegisterService(&_Grapery_serviceDesc, srv)
}

func _Grapery_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraperyServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grapery.api.Grapery/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraperyServer).PingPong(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grapery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grapery.api.Grapery",
	HandlerType: (*GraperyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _Grapery_PingPong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/grapery/grapery/pb/service.proto",
}
