FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
ENV GO111MODULE=on GOPROXY=https://goproxy.cn,direct CGO_ENABLED=0 GOOS=linux
RUN go build -o grapes-app ./app/grapes

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
ENV TZ=Asia/Shanghai
WORKDIR /app
RUN echo "====COPY前 /app 目录内容 ====" && ls -l /app
COPY --from=builder /app/grapes-app .
COPY app.json /app/app.json
RUN echo "====COPY后 /app 目录内容 ====" && ls -l /app
EXPOSE 8080
CMD ["./grapes-app", "--config", "/app/app.json"] 
