FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
ENV GO111MODULE=on GOPROXY=https://goproxy.cn,direct CGO_ENABLED=0 GOOS=linux
RUN go build -o grapes-vippay ./app/vippay

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
ENV TZ=Asia/Shanghai
WORKDIR /app
COPY --from=builder /app/grapes-vippay .
COPY configs/ /app/configs/
EXPOSE 8080
CMD ["./grapes-vippay"] 