FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
ENV GO111MODULE=on GOPROXY=https://goproxy.cn,direct CGO_ENABLED=0 GOOS=linux
RUN go build -o grapes-app ./app/grapes

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
ENV TZ=Asia/Shanghai
WORKDIR /app
COPY --from=builder /app/grapes-app .
COPY config.json /app/config.json
EXPOSE 8080
CMD ["./grapes-app"] 
