package domain

// AITaskType AI 任务类型
type AITaskType string

const (
	AITaskGenerateStory AITaskType = "generate_story"
	AITaskEnhancePrompt AITaskType = "enhance_prompt"
	AITaskGenerateImage AITaskType = "generate_image"
	AITaskGenerateVideo AITaskType = "generate_video"
)

// AITaskStatus AI 任务状态
type AITaskStatus string

const (
	AITaskStatusPending    AITaskStatus = "pending"
	AITaskStatusProcessing AITaskStatus = "processing"
	AITaskStatusCompleted  AITaskStatus = "completed"
	AITaskStatusFailed     AITaskStatus = "failed"
	AITaskStatusCancelled  AITaskStatus = "cancelled"
)

// AITask AI 任务
type AITask struct {
	ID                string       `json:"id"`
	UserID            string       `json:"userId"`
	Type              AITaskType   `json:"type"`
	Status            AITaskStatus `json:"status"`
	Provider          string       `json:"provider"` // huoshan, gemini, etc.
	Model             string       `json:"model,omitempty"`
	Input             string       `json:"input"`            // JSON 格式的输入参数
	Output            string       `json:"output,omitempty"` // JSON 格式的输出结果
	TokensUsed        int          `json:"tokensUsed"`
	Progress          int          `json:"progress"` // 0-100
	ErrorMessage      string       `json:"errorMessage,omitempty"`
	RelatedEntityID   string       `json:"relatedEntityId,omitempty"`   // 关联的故事/故事板ID
	RelatedEntityType string       `json:"relatedEntityType,omitempty"` // story, storyboard
	CreatedAt         int64        `json:"createdAt"`
	StartedAt         *int64       `json:"startedAt,omitempty"`
	CompletedAt       *int64       `json:"completedAt,omitempty"`
	UpdatedAt         int64        `json:"updatedAt"`

	// Relations
	User *User `json:"user,omitempty"`
}

// AIStoryGenerationRequest AI 故事生成请求
type AIStoryGenerationRequest struct {
	Prompt      string   `json:"prompt"`
	Context     string   `json:"context,omitempty"`     // 上下文信息
	Characters  []string `json:"characters,omitempty"`  // 角色ID列表
	Style       string   `json:"style,omitempty"`       // 风格：fantasy, scifi, etc.
	Length      string   `json:"length,omitempty"`      // short, medium, long
	Temperature float64  `json:"temperature,omitempty"` // 0-1
}

// AIGeneratedScene represents a scene generated by AI (used in story/storyboard generation)
type AIGeneratedScene struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Location    string `json:"location,omitempty"`
	TimeOfDay   string `json:"timeOfDay,omitempty"`
}

// AIStoryGenerationResult AI 故事生成结果
type AIStoryGenerationResult struct {
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Summary       string             `json:"summary,omitempty"`
	Scenes        []AIGeneratedScene `json:"scenes,omitempty"`
	SuggestedTags []string           `json:"suggestedTags,omitempty"`
	TokensUsed    int                `json:"tokensUsed"`
}

// AIPromptEnhanceRequest AI 提示词增强请求
type AIPromptEnhanceRequest struct {
	OriginalPrompt string `json:"originalPrompt"`
	TargetType     string `json:"targetType"`            // image, video, storyboard
	Style          string `json:"style,omitempty"`       // 风格
	DetailLevel    string `json:"detailLevel,omitempty"` // low, medium, high
}

// AIPromptEnhanceResult AI 提示词增强结果
type AIPromptEnhanceResult struct {
	EnhancedPrompt string `json:"enhancedPrompt"`
	Improvements   string `json:"improvements,omitempty"` // 改进说明
	TokensUsed     int    `json:"tokensUsed"`
}

// AIImageGenerationRequest AI 图片生成请求
type AIImageGenerationRequest struct {
	Prompt  string `json:"prompt"`
	Size    string `json:"size,omitempty"`    // 1024x1024, 512x512, etc.
	Quality string `json:"quality,omitempty"` // standard, hd
	Style   string `json:"style,omitempty"`   // vivid, natural
	N       int    `json:"n,omitempty"`       // 生成图片数量
}

// AIImageGenerationResult AI 图片生成结果
type AIImageGenerationResult struct {
	URLs       []string `json:"urls"`
	TokensUsed int      `json:"tokensUsed"`
}

// AIVideoGenerationRequest AI 视频生成请求
type AIVideoGenerationRequest struct {
	Prompt      string   `json:"prompt"`
	Duration    int      `json:"duration,omitempty"`   // 秒
	Resolution  string   `json:"resolution,omitempty"` // 720p, 1080p, 4k
	FrameRate   int      `json:"frameRate,omitempty"`  // 24, 30, 60
	Style       string   `json:"style,omitempty"`
	StartFrame  string   `json:"startFrame,omitempty"`  // 起始帧图片URL
	EndFrame    string   `json:"endFrame,omitempty"`    // 结束帧图片URL
	SceneImages []string `json:"sceneImages,omitempty"` // 场景图片列表
}

// AIVideoGenerationResult AI 视频生成结果
type AIVideoGenerationResult struct {
	VideoURL     string `json:"videoUrl"`
	ThumbnailURL string `json:"thumbnailUrl,omitempty"`
	Duration     int    `json:"duration"` // 实际视频时长（秒）
	TokensUsed   int    `json:"tokensUsed"`
}

// AIGenerationRecord AI 生成记录 - 记录AI能力使用数据，用于任务管理和计费
type AIGenerationRecord struct {
	ID       string `json:"id"`
	UserID   string `json:"userId"`
	Type     string `json:"type"`     // text, image, video, audio
	Provider string `json:"provider"` // gemini, hailuo, huoshan, qwen
	Model    string `json:"model"`

	// 提示词信息
	OriginalPrompt string `json:"originalPrompt"`           // 原始提示词
	EnhancedPrompt string `json:"enhancedPrompt,omitempty"` // 增强后的提示词
	SystemPrompt   string `json:"systemPrompt,omitempty"`   // 系统提示词

	// 输入输出（JSON格式）
	InputParams  string `json:"inputParams,omitempty"`  // 完整的输入参数（JSON）
	OutputResult string `json:"outputResult,omitempty"` // 完整的输出结果（JSON）

	// Token 消耗统计
	InputTokens  int `json:"inputTokens"`  // 输入 token 数
	OutputTokens int `json:"outputTokens"` // 输出 token 数
	TotalTokens  int `json:"totalTokens"`  // 总 token 数
	ImageCount   int `json:"imageCount"`   // 生成图片数量
	VideoCount   int `json:"videoCount"`   // 生成视频数量

	// 重试统计
	RetryCount int `json:"retryCount"` // 重试次数

	// 风格设置
	Style string `json:"style,omitempty"` // 生成风格

	// 任务状态
	Status       AITaskStatus `json:"status"`                 // pending, processing, completed, failed
	Progress     int          `json:"progress"`               // 0-100
	ErrorMessage string       `json:"errorMessage,omitempty"` // 错误信息
	ErrorCode    string       `json:"errorCode,omitempty"`    // 错误码

	// 时间统计（毫秒）
	DurationMs    int64 `json:"durationMs"`    // 总耗时
	QueueTimeMs   int64 `json:"queueTimeMs"`   // 排队时间
	ProcessTimeMs int64 `json:"processTimeMs"` // 处理时间

	// 关联的业务实体
	RelatedEntityID   string `json:"relatedEntityId,omitempty"`   // 关联实体ID
	RelatedEntityType string `json:"relatedEntityType,omitempty"` // story, storyboard, character, poster

	// 时间戳
	CreatedAt   int64  `json:"createdAt"`             // 创建时间
	StartedAt   *int64 `json:"startedAt,omitempty"`   // 开始处理时间
	CompletedAt *int64 `json:"completedAt,omitempty"` // 完成时间

	// 额外元数据
	Metadata map[string]interface{} `json:"metadata,omitempty"` // 扩展元数据

	// Relations
	User *User `json:"user,omitempty"`
}

// RenderTaskType 渲染任务类型
type RenderTaskType string

const (
	RenderTaskTypeVideo     RenderTaskType = "video"
	RenderTaskTypeImageSet  RenderTaskType = "image_set"
	RenderTaskTypeAnimation RenderTaskType = "animation"
)

// RenderTaskStatus 渲染任务状态
type RenderTaskStatus string

const (
	RenderTaskStatusPending    RenderTaskStatus = "pending"
	RenderTaskStatusProcessing RenderTaskStatus = "processing"
	RenderTaskStatusCompleted  RenderTaskStatus = "completed"
	RenderTaskStatusFailed     RenderTaskStatus = "failed"
	RenderTaskStatusCancelled  RenderTaskStatus = "cancelled"
)

// RenderTask 渲染任务
type RenderTask struct {
	ID           string           `json:"id"`
	UserID       string           `json:"userId"`
	StoryID      string           `json:"storyId"`
	Type         RenderTaskType   `json:"type"`
	Status       RenderTaskStatus `json:"status"`
	Config       string           `json:"config"` // JSON 格式的渲染配置
	OutputURL    string           `json:"outputUrl,omitempty"`
	ThumbnailURL string           `json:"thumbnailUrl,omitempty"`
	Progress     int              `json:"progress"` // 0-100
	ErrorMessage string           `json:"errorMessage,omitempty"`
	FileSize     int64            `json:"fileSize,omitempty"` // 字节
	Duration     int              `json:"duration,omitempty"` // 视频时长（秒）
	Resolution   string           `json:"resolution,omitempty"`
	CreatedAt    int64            `json:"createdAt"`
	StartedAt    *int64           `json:"startedAt,omitempty"`
	CompletedAt  *int64           `json:"completedAt,omitempty"`
	UpdatedAt    int64            `json:"updatedAt"`

	// Relations
	User  *User  `json:"user,omitempty"`
	Story *Story `json:"story,omitempty"`
}

// RenderConfig 渲染配置
type RenderConfig struct {
	Type        RenderTaskType `json:"type"`
	Resolution  string         `json:"resolution,omitempty"`  // 720p, 1080p, 4k
	FrameRate   int            `json:"frameRate,omitempty"`   // 24, 30, 60
	Quality     string         `json:"quality,omitempty"`     // low, medium, high
	Format      string         `json:"format,omitempty"`      // mp4, webm, gif
	Duration    int            `json:"duration,omitempty"`    // 总时长（秒）
	Transitions string         `json:"transitions,omitempty"` // fade, slide, zoom
	BGM         string         `json:"bgm,omitempty"`         // 背景音乐URL
	Narration   bool           `json:"narration,omitempty"`   // 是否添加旁白
	Subtitles   bool           `json:"subtitles,omitempty"`   // 是否添加字幕
}
