package domain

import "github.com/grapestree/fgrapery/grapery/internal/common"

// StoryboardRootMarker is the special marker for root storyboard's ParentID
const StoryboardRootMarker = "__root__"

// StoryboardScene represents an AI-generated plot scene within a storyboard.
// This is different from StoryScene which is a static location belonging to a Story.
// StoryboardScene is dynamic content generated based on user input, characters, and selected StoryScenes.
type StoryboardScene struct {
	// Base model fields
	common.BaseModel

	StoryboardID  string   `json:"storyboardId"`
	StorySceneID  string   `json:"storySceneId,omitempty"` // Optional link to story scene (location)
	Sequence      int      `json:"sequence"`
	Title         string   `json:"title"`
	Description   string   `json:"description"`
	Image         string   `json:"image,omitempty"`
	VideoUrl      string   `json:"videoUrl,omitempty"` // Generated video URL (from StoryboardVideoGeneration)
	Location      string   `json:"location,omitempty"` // AI-generated or from StoryScene
	TimeOfDay     string   `json:"timeOfDay,omitempty"`
	Characters    []string `json:"characters,omitempty"` // Character names in this scene
	Mood          string   `json:"mood,omitempty"`
	IsAIGenerated bool     `json:"isAIGenerated"`

	// Keyframe Subdivision fields
	VideoSegments     []VideoSegmentInfo `json:"videoSegments,omitempty"`   // Video segments when subdivision is applied
	MiddleFrameURLs   []string           `json:"middleFrameUrls,omitempty"` // Generated middle frame URLs
	IsSubdivided      bool               `json:"isSubdivided"`              // Whether keyframe subdivision was applied
	VideoSegmentsJSON string             `json:"-"`                         // JSON storage for database

	// 平行宇宙系统字段
	ContextSnapshot string `json:"contextSnapshot,omitempty"` // 该场景结束后的角色状态增量 (JSON)

	// Storyboard generation redesign metadata
	GenerationRunID string   `json:"generationRunId,omitempty"`
	BeatIndex       int      `json:"beatIndex,omitempty"`
	BeatPurpose     string   `json:"beatPurpose,omitempty"`
	ContinuityNote  string   `json:"continuityNote,omitempty"`
	ReferenceKeys   []string `json:"referenceKeys,omitempty"`
	ImagePrompt     string   `json:"imagePrompt,omitempty"`
	VisualStateJSON string   `json:"visualState,omitempty"`
	// ComicTexts 本格漫画文字层（对白/思想泡/拟声/旁白），由文本/分镜阶段产出并透传到生图。
	ComicTexts []StoryboardComicText `json:"comicTexts,omitempty"`
	// 漫画构图元数据：用于图片/漫画页阶段直接消费，不再仅靠二次推断。
	LayoutIntent    string `json:"layoutIntent,omitempty"`
	CompositionPlan string `json:"compositionPlan,omitempty"`
	ShotType        string `json:"shotType,omitempty"`
	VisualHierarchy string `json:"visualHierarchy,omitempty"`
	// PanelShape 决定本格在多格拼贴封面中的裁切形状。
	// AI 根据剧情情绪（comicFunction）赋值；前端 collage view 直接消费。
	// 允许值：full | diagonal_left | diagonal_right |
	//         trapezoid_leading | trapezoid_trailing |
	//         triangle_tl | triangle_tr | triangle_bl | triangle_br |
	//         wide_panorama
	PanelShape string `json:"panelShape,omitempty"`

	// Relations
	StoryScene *StoryScene `json:"storyScene,omitempty"`
}

// VideoSegmentInfo represents a video segment in the storyboard scene.
type VideoSegmentInfo struct {
	Index        int    `json:"index"`        // Segment sequence number (0-based)
	VideoURL     string `json:"videoUrl"`     // Video URL
	StartFrame   string `json:"startFrame"`   // Start keyframe URL
	EndFrame     string `json:"endFrame"`     // End keyframe URL
	DurationSecs int    `json:"durationSecs"` // Duration in seconds
}

// StoryboardCharacter represents a character reference in a storyboard
type StoryboardCharacter struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Role   string `json:"role"`
}

// Storyboard represents a storyboard node with tree structure (支持 Fork 和续写)
type Storyboard struct {
	// Base model fields
	common.BaseModel

	StoryID       string `json:"storyId"`
	ParentID      string `json:"parentId"`  // StoryboardRootMarker ("__root__") for root storyboard
	UserID        string `json:"creatorId"` // 保持 JSON 标签为 creatorId 以保持 API 兼容性
	CreatorName   string `json:"creatorName"`
	CreatorAvatar string `json:"creatorAvatar"`
	Title         string `json:"title"`
	Content       string `json:"content"`  // AI-polished narrative
	RawInput      string `json:"rawInput"` // Original user input/prompt
	// ContinuationSummary is a lossy narrative summary for fork/continuation context (optional in API).
	ContinuationSummary string `json:"continuationSummary,omitempty"`
	IsStandalone        bool   `json:"isStandalone"`   // Independent plot, AI won't reference parent context
	IsAIGenerated       bool   `json:"isAIGenerated"`  // Content was generated by AI
	SceneCount          int    `json:"sceneCount"`     // Requested number of scenes to generate (2-8, default 3)
	WorkflowStatus      string `json:"workflowStatus"` // draft, content_ready, images_ready, video_ready, published
	CurrentStep         int    `json:"currentStep"`    // 1-5 (setup, create, images, video, publish)

	// 续写 / 创作选项（持久化；默认仅生图，勾选后生图完成再基于首帧图生视频）
	GenerateVideoAfterImages bool   `json:"generateVideoAfterImages"` // 默认 false
	ContinuationComicStyle   string `json:"comicStyle,omitempty"`     // 漫画风格 slug（如日系动漫），可选
	// UseComicPagePipeline 为 true 时：分镜就绪后不自动拉 GenerateSceneImage，由客户端走 generate/comic-page(s)，避免单图抢跑导致漫画管线被 skip
	UseComicPagePipeline bool `json:"useComicPagePipeline,omitempty"`

	// Engagement stats fields
	common.EngagementStats

	ForkCount        int `json:"forkCount"`
	TokenConsumption int `json:"tokenConsumption"` // Aggregated from all generation records

	// StoryboardScenes are AI-generated plot scenes belonging to this storyboard
	StoryboardScenes []StoryboardScene `json:"storyboardScenes,omitempty"`

	// Linked assets - references to story-level resources
	CharacterRefs []StoryboardCharacterRef `json:"characterRefs,omitempty"`
	SceneRefs     []StoryboardSceneRef     `json:"sceneRefs,omitempty"` // Links to StoryScene (static locations)
	ChildrenIds   []string                 `json:"childrenIds,omitempty"`

	// 平行宇宙系统字段
	FateSnapshot     *string `json:"fateSnapshot,omitempty"`     // 分叉时刻所有角色的状态 (JSON)
	FateSnapshotHash *string `json:"fateSnapshotHash,omitempty"` // 命运快照哈希值（用于快速比较）

	// Relations
	Story   *Story `json:"story,omitempty"`
	Creator *User  `json:"creator,omitempty"`

	// 是否是默认路径节点
	IsInDefaultPath bool `json:"isInDefaultPath,omitempty" gorm:"default:false"`

	// 在默认路径中的顺序（用于排序）
	DefaultPathOrder int `json:"defaultPathOrder,omitempty" gorm:"default:0"`

	// 当前登录用户是否已点赞（仅 API 响应填充，非 storyboards 表字段）
	IsLiked *bool `json:"isLiked,omitempty" gorm:"-"`
}

// StoryboardLike Storyboard 点赞
type StoryboardLike struct {
	// Base model fields
	common.BaseModel

	UserID       string `json:"userId"`
	StoryboardID string `json:"storyboardId"`

	// Relations
	User       *User       `json:"user,omitempty"`
	Storyboard *Storyboard `json:"storyboard,omitempty"`
}

// StoryParticipant represents a participant in a story composition
type StoryParticipant struct {
	// Base model fields
	common.BaseModel

	UserID   string `json:"userId"`
	Name     string `json:"name"`
	Avatar   string `json:"avatar"`
	Role     string `json:"role"` // owner, collaborator, contributor
	JoinedAt int64  `json:"joinedAt"`
}

// StoryComposition represents a story composition with multiple storyboards
type StoryComposition struct {
	// Base model fields
	common.BaseModel

	Title                 string `json:"title"`
	CoverImage            string `json:"coverImage"`
	BackgroundDescription string `json:"backgroundDescription"`
	Theme                 string `json:"theme"`
	Genre                 string `json:"genre"`
	RootStoryboardID      string `json:"rootStoryboardId"`
	ParticipantsJSON      string `json:"-"`
	TotalStoryboards      int    `json:"totalStoryboards"`
	TotalForks            int    `json:"totalForks"`

	// Business fields
	Participants []StoryParticipant `json:"participants,omitempty"`
}

// StoryboardStatus 故事板状态 - 使用 common.ContentStatus 作为类型别名以保持向后兼容
type StoryboardStatus = common.ContentStatus

const (
	StoryboardStatusDraft     StoryboardStatus = common.ContentStatusDraft
	StoryboardStatusPublished StoryboardStatus = common.ContentStatusPublished
)

// StoryboardPanel 故事板面板（用于分支选择器展示）
type StoryboardPanel struct {
	common.BaseModel

	StoryboardID string `json:"storyboardId"`
	Sequence     int    `json:"sequence"`

	ImageURL  string `json:"img"`
	Text      string `json:"text"`
	TextPos   string `json:"textPos,omitempty"`
	TextRight string `json:"textRight,omitempty"`

	IsAIGenerated bool   `json:"isAIGenerated"`
	Prompt        string `json:"prompt,omitempty"`

	// Relations
	Storyboard *Storyboard `json:"storyboard,omitempty"`
}

// ForkStoryboardRequest 创建分支请求
type ForkStoryboardRequest struct {
	Direction     string `json:"direction"`               // 分支方向描述
	Style         string `json:"style,omitempty"`         // 风格选择
	PanelCount    int    `json:"panelCount,omitempty"`    // 面板数量
	ParentPanelID string `json:"parentPanelId,omitempty"` // 从哪个面板分叉
}

// StoryboardWithPanels 带面板的故事板（用于分支选择器）
type StoryboardWithPanels struct {
	Storyboard
	Panels []StoryboardPanel `json:"panels,omitempty"`
}
