package domain

// StoryboardRootMarker is the special marker for root storyboard's ParentID
const StoryboardRootMarker = "__root__"

// StoryboardScene represents an AI-generated plot scene within a storyboard.
// This is different from StoryScene which is a static location belonging to a Story.
// StoryboardScene is dynamic content generated based on user input, characters, and selected StoryScenes.
type StoryboardScene struct {
	ID            string   `json:"id"`
	StoryboardID  string   `json:"storyboardId"`
	StorySceneID  string   `json:"storySceneId,omitempty"` // Optional link to story scene (location)
	Sequence      int      `json:"sequence"`
	Title         string   `json:"title"`
	Description   string   `json:"description"`
	Image         string   `json:"image,omitempty"`
	VideoUrl      string   `json:"videoUrl,omitempty"` // Generated video URL (from StoryboardVideoGeneration)
	Location      string   `json:"location,omitempty"` // AI-generated or from StoryScene
	TimeOfDay     string   `json:"timeOfDay,omitempty"`
	Characters    []string `json:"characters,omitempty"` // Character names in this scene
	Mood          string   `json:"mood,omitempty"`
	IsAIGenerated bool     `json:"isAIGenerated"`
	CreatedAt     int64    `json:"createdAt"`
	UpdatedAt     int64    `json:"updatedAt"`

	// Keyframe Subdivision fields
	VideoSegments     []VideoSegmentInfo `json:"videoSegments,omitempty"`   // Video segments when subdivision is applied
	MiddleFrameURLs   []string           `json:"middleFrameUrls,omitempty"` // Generated middle frame URLs
	IsSubdivided      bool               `json:"isSubdivided"`              // Whether keyframe subdivision was applied
	VideoSegmentsJSON string             `json:"-"`                         // JSON storage for database

	// 平行宇宙系统字段
	ContextSnapshot string `json:"contextSnapshot,omitempty"` // 该场景结束后的角色状态增量 (JSON)

	// Relations
	StoryScene *StoryScene `json:"storyScene,omitempty"`
}

// VideoSegmentInfo represents a video segment in the storyboard scene.
type VideoSegmentInfo struct {
	Index        int    `json:"index"`        // Segment sequence number (0-based)
	VideoURL     string `json:"videoUrl"`     // Video URL
	StartFrame   string `json:"startFrame"`   // Start keyframe URL
	EndFrame     string `json:"endFrame"`     // End keyframe URL
	DurationSecs int    `json:"durationSecs"` // Duration in seconds
}

// StoryboardCharacter represents a character reference in a storyboard
type StoryboardCharacter struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Role   string `json:"role"`
}

// Storyboard represents a storyboard node with tree structure (支持 Fork 和续写)
type Storyboard struct {
	ID               string `json:"id"`
	StoryID          string `json:"storyId"`
	ParentID         string `json:"parentId"` // StoryboardRootMarker ("__root__") for root storyboard
	CreatorID        string `json:"creatorId"`
	CreatorName      string `json:"creatorName"`
	CreatorAvatar    string `json:"creatorAvatar"`
	Title            string `json:"title"`
	Content          string `json:"content"`        // AI-polished narrative
	RawInput         string `json:"rawInput"`       // Original user input/prompt
	IsStandalone     bool   `json:"isStandalone"`   // Independent plot, AI won't reference parent context
	IsAIGenerated    bool   `json:"isAIGenerated"`  // Content was generated by AI
	SceneCount       int    `json:"sceneCount"`     // Requested number of scenes to generate (2-5, default 3)
	WorkflowStatus   string `json:"workflowStatus"` // draft, content_ready, images_ready, video_ready, published
	CurrentStep      int    `json:"currentStep"`    // 1-5 (setup, create, images, video, publish)
	Likes            int    `json:"likes"`
	Comments         int    `json:"comments"`
	Shares           int    `json:"shares"`
	ForkCount        int    `json:"forkCount"`
	Views            int    `json:"views"`
	TokenConsumption int    `json:"tokenConsumption"` // Aggregated from all generation records
	CreatedAt        int64  `json:"createdAt"`
	UpdatedAt        int64  `json:"updatedAt"`

	// StoryboardScenes are AI-generated plot scenes belonging to this storyboard
	StoryboardScenes []StoryboardScene `json:"storyboardScenes,omitempty"`

	// Linked assets - references to story-level resources
	CharacterRefs []StoryboardCharacterRef `json:"characterRefs,omitempty"`
	SceneRefs     []StoryboardSceneRef     `json:"sceneRefs,omitempty"` // Links to StoryScene (static locations)
	ChildrenIds   []string                 `json:"childrenIds,omitempty"`

	// 平行宇宙系统字段
	FateSnapshot     *string `json:"fateSnapshot,omitempty"`      // 分叉时刻所有角色的状态 (JSON)
	FateSnapshotHash *string `json:"fateSnapshotHash,omitempty"`  // 命运快照哈希值（用于快速比较）

	// Relations
	Story   *Story `json:"story,omitempty"`
	Creator *User  `json:"creator,omitempty"`

	// 是否是默认路径节点
	IsInDefaultPath bool `json:"isInDefaultPath,omitempty" gorm:"default:false"`

	// 在默认路径中的顺序（用于排序）
	DefaultPathOrder int `json:"defaultPathOrder,omitempty" gorm:"default:0"`
}

// StoryboardLike Storyboard 点赞
type StoryboardLike struct {
	ID           string `json:"id"`
	UserID       string `json:"userId"`
	StoryboardID string `json:"storyboardId"`
	CreatedAt    int64  `json:"createdAt"`

	// Relations
	User       *User       `json:"user,omitempty"`
	Storyboard *Storyboard `json:"storyboard,omitempty"`
}

// StoryParticipant represents a participant in a story composition
type StoryParticipant struct {
	ID       string `json:"id"`
	UserID   string `json:"userId"`
	Name     string `json:"name"`
	Avatar   string `json:"avatar"`
	Role     string `json:"role"` // owner, collaborator, contributor
	JoinedAt int64  `json:"joinedAt"`
}

// StoryComposition represents a story composition with multiple storyboards
type StoryComposition struct {
	ID                    string `json:"id"`
	Title                 string `json:"title"`
	CoverImage            string `json:"coverImage"`
	BackgroundDescription string `json:"backgroundDescription"`
	Theme                 string `json:"theme"`
	Genre                 string `json:"genre"`
	RootStoryboardID      string `json:"rootStoryboardId"`
	ParticipantsJSON      string `json:"-"`
	TotalStoryboards      int    `json:"totalStoryboards"`
	TotalForks            int    `json:"totalForks"`
	CreatedAt             int64  `json:"createdAt"`
	UpdatedAt             int64  `json:"updatedAt"`

	// Business fields
	Participants []StoryParticipant `json:"participants,omitempty"`
}
