// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: github.com/grapery/grapery/common-protoc/comment.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ContentMultiError, or nil if none found.
func (m *Content) ValidateAll() error {
	return m.validate(true)
}

func (m *Content) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ctype

	// no validation rules for Length

	// no validation rules for Version

	// no validation rules for Data

	if len(errors) > 0 {
		return ContentMultiError(errors)
	}

	return nil
}

// ContentMultiError is an error wrapping multiple validation errors returned
// by Content.ValidateAll() if the designated constraints aren't met.
type ContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContentMultiError) AllErrors() []error { return m }

// ContentValidationError is the validation error returned by Content.Validate
// if the designated constraints aren't met.
type ContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContentValidationError) ErrorName() string { return "ContentValidationError" }

// Error satisfies the builtin error interface
func (e ContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContentValidationError{}

// Validate checks the field values on CreateCommentReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateCommentReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCommentReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCommentReqMultiError, or nil if none found.
func (m *CreateCommentReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCommentReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ItemId

	if len(errors) > 0 {
		return CreateCommentReqMultiError(errors)
	}

	return nil
}

// CreateCommentReqMultiError is an error wrapping multiple validation errors
// returned by CreateCommentReq.ValidateAll() if the designated constraints
// aren't met.
type CreateCommentReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCommentReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCommentReqMultiError) AllErrors() []error { return m }

// CreateCommentReqValidationError is the validation error returned by
// CreateCommentReq.Validate if the designated constraints aren't met.
type CreateCommentReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCommentReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCommentReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCommentReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCommentReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCommentReqValidationError) ErrorName() string { return "CreateCommentReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateCommentReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCommentReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCommentReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCommentReqValidationError{}

// Validate checks the field values on CreateCommentResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateCommentResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCommentRespMultiError, or nil if none found.
func (m *CreateCommentResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCommentResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateCommentRespMultiError(errors)
	}

	return nil
}

// CreateCommentRespMultiError is an error wrapping multiple validation errors
// returned by CreateCommentResp.ValidateAll() if the designated constraints
// aren't met.
type CreateCommentRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCommentRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCommentRespMultiError) AllErrors() []error { return m }

// CreateCommentRespValidationError is the validation error returned by
// CreateCommentResp.Validate if the designated constraints aren't met.
type CreateCommentRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCommentRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCommentRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCommentRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCommentRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCommentRespValidationError) ErrorName() string {
	return "CreateCommentRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCommentRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCommentResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCommentRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCommentRespValidationError{}

// Validate checks the field values on GetItemCommentReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetItemCommentReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetItemCommentReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetItemCommentReqMultiError, or nil if none found.
func (m *GetItemCommentReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetItemCommentReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ItemId

	if len(errors) > 0 {
		return GetItemCommentReqMultiError(errors)
	}

	return nil
}

// GetItemCommentReqMultiError is an error wrapping multiple validation errors
// returned by GetItemCommentReq.ValidateAll() if the designated constraints
// aren't met.
type GetItemCommentReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetItemCommentReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetItemCommentReqMultiError) AllErrors() []error { return m }

// GetItemCommentReqValidationError is the validation error returned by
// GetItemCommentReq.Validate if the designated constraints aren't met.
type GetItemCommentReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetItemCommentReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetItemCommentReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetItemCommentReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetItemCommentReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetItemCommentReqValidationError) ErrorName() string {
	return "GetItemCommentReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetItemCommentReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetItemCommentReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetItemCommentReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetItemCommentReqValidationError{}

// Validate checks the field values on GetItemCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetItemCommentResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetItemCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetItemCommentRespMultiError, or nil if none found.
func (m *GetItemCommentResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetItemCommentResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetItemCommentRespMultiError(errors)
	}

	return nil
}

// GetItemCommentRespMultiError is an error wrapping multiple validation errors
// returned by GetItemCommentResp.ValidateAll() if the designated constraints
// aren't met.
type GetItemCommentRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetItemCommentRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetItemCommentRespMultiError) AllErrors() []error { return m }

// GetItemCommentRespValidationError is the validation error returned by
// GetItemCommentResp.Validate if the designated constraints aren't met.
type GetItemCommentRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetItemCommentRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetItemCommentRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetItemCommentRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetItemCommentRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetItemCommentRespValidationError) ErrorName() string {
	return "GetItemCommentRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetItemCommentRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetItemCommentResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetItemCommentRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetItemCommentRespValidationError{}

// Validate checks the field values on GetUserCommentReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserCommentReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCommentReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCommentReqMultiError, or nil if none found.
func (m *GetUserCommentReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCommentReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUserCommentReqMultiError(errors)
	}

	return nil
}

// GetUserCommentReqMultiError is an error wrapping multiple validation errors
// returned by GetUserCommentReq.ValidateAll() if the designated constraints
// aren't met.
type GetUserCommentReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCommentReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCommentReqMultiError) AllErrors() []error { return m }

// GetUserCommentReqValidationError is the validation error returned by
// GetUserCommentReq.Validate if the designated constraints aren't met.
type GetUserCommentReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCommentReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCommentReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCommentReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCommentReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCommentReqValidationError) ErrorName() string {
	return "GetUserCommentReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCommentReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCommentReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCommentReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCommentReqValidationError{}

// Validate checks the field values on GetUserCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserCommentResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserCommentRespMultiError, or nil if none found.
func (m *GetUserCommentResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserCommentResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUserCommentRespMultiError(errors)
	}

	return nil
}

// GetUserCommentRespMultiError is an error wrapping multiple validation errors
// returned by GetUserCommentResp.ValidateAll() if the designated constraints
// aren't met.
type GetUserCommentRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserCommentRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserCommentRespMultiError) AllErrors() []error { return m }

// GetUserCommentRespValidationError is the validation error returned by
// GetUserCommentResp.Validate if the designated constraints aren't met.
type GetUserCommentRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCommentRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCommentRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCommentRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCommentRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCommentRespValidationError) ErrorName() string {
	return "GetUserCommentRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCommentRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCommentResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCommentRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCommentRespValidationError{}
