// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: github.com/grapery/grapery/common-protoc/comment.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Content) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Ctype

	// no validation rules for Length

	// no validation rules for Version

	// no validation rules for Data

	return nil
}

// ContentValidationError is the validation error returned by Content.Validate
// if the designated constraints aren't met.
type ContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContentValidationError) ErrorName() string { return "ContentValidationError" }

// Error satisfies the builtin error interface
func (e ContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContentValidationError{}

// Validate checks the field values on CreateCommentReq with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *CreateCommentReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ItemId

	return nil
}

// CreateCommentReqValidationError is the validation error returned by
// CreateCommentReq.Validate if the designated constraints aren't met.
type CreateCommentReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCommentReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCommentReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCommentReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCommentReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCommentReqValidationError) ErrorName() string { return "CreateCommentReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateCommentReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCommentReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCommentReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCommentReqValidationError{}

// Validate checks the field values on CreateCommentResp with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *CreateCommentResp) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// CreateCommentRespValidationError is the validation error returned by
// CreateCommentResp.Validate if the designated constraints aren't met.
type CreateCommentRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCommentRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCommentRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCommentRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCommentRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCommentRespValidationError) ErrorName() string {
	return "CreateCommentRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCommentRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCommentResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCommentRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCommentRespValidationError{}

// Validate checks the field values on GetItemCommentReq with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetItemCommentReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ItemId

	return nil
}

// GetItemCommentReqValidationError is the validation error returned by
// GetItemCommentReq.Validate if the designated constraints aren't met.
type GetItemCommentReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetItemCommentReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetItemCommentReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetItemCommentReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetItemCommentReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetItemCommentReqValidationError) ErrorName() string {
	return "GetItemCommentReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetItemCommentReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetItemCommentReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetItemCommentReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetItemCommentReqValidationError{}

// Validate checks the field values on GetItemCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetItemCommentResp) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetItemCommentRespValidationError is the validation error returned by
// GetItemCommentResp.Validate if the designated constraints aren't met.
type GetItemCommentRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetItemCommentRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetItemCommentRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetItemCommentRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetItemCommentRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetItemCommentRespValidationError) ErrorName() string {
	return "GetItemCommentRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetItemCommentRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetItemCommentResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetItemCommentRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetItemCommentRespValidationError{}

// Validate checks the field values on GetUserProjectCommentReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetUserProjectCommentReq) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetUserProjectCommentReqValidationError is the validation error returned by
// GetUserProjectCommentReq.Validate if the designated constraints aren't met.
type GetUserProjectCommentReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserProjectCommentReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserProjectCommentReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserProjectCommentReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserProjectCommentReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserProjectCommentReqValidationError) ErrorName() string {
	return "GetUserProjectCommentReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserProjectCommentReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserProjectCommentReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserProjectCommentReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserProjectCommentReqValidationError{}

// Validate checks the field values on GetUserProjectCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetUserProjectCommentResp) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetUserProjectCommentRespValidationError is the validation error returned by
// GetUserProjectCommentResp.Validate if the designated constraints aren't met.
type GetUserProjectCommentRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserProjectCommentRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserProjectCommentRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserProjectCommentRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserProjectCommentRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserProjectCommentRespValidationError) ErrorName() string {
	return "GetUserProjectCommentRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserProjectCommentRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserProjectCommentResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserProjectCommentRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserProjectCommentRespValidationError{}

// Validate checks the field values on GetUserCommentReq with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetUserCommentReq) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetUserCommentReqValidationError is the validation error returned by
// GetUserCommentReq.Validate if the designated constraints aren't met.
type GetUserCommentReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCommentReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCommentReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCommentReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCommentReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCommentReqValidationError) ErrorName() string {
	return "GetUserCommentReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCommentReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCommentReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCommentReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCommentReqValidationError{}

// Validate checks the field values on GetUserCommentResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetUserCommentResp) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetUserCommentRespValidationError is the validation error returned by
// GetUserCommentResp.Validate if the designated constraints aren't met.
type GetUserCommentRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserCommentRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserCommentRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserCommentRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserCommentRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserCommentRespValidationError) ErrorName() string {
	return "GetUserCommentRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserCommentRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserCommentResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserCommentRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserCommentRespValidationError{}
