// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: github.com/grapery/grapery/common-protoc/item.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetProjectItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProjectItemsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProjectItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProjectItemsRequestMultiError, or nil if none found.
func (m *GetProjectItemsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProjectItemsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	if len(errors) > 0 {
		return GetProjectItemsRequestMultiError(errors)
	}

	return nil
}

// GetProjectItemsRequestMultiError is an error wrapping multiple validation
// errors returned by GetProjectItemsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetProjectItemsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProjectItemsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProjectItemsRequestMultiError) AllErrors() []error { return m }

// GetProjectItemsRequestValidationError is the validation error returned by
// GetProjectItemsRequest.Validate if the designated constraints aren't met.
type GetProjectItemsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectItemsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectItemsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectItemsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectItemsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectItemsRequestValidationError) ErrorName() string {
	return "GetProjectItemsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectItemsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectItemsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectItemsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectItemsRequestValidationError{}

// Validate checks the field values on GetProjectItemsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProjectItemsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProjectItemsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProjectItemsResponseMultiError, or nil if none found.
func (m *GetProjectItemsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProjectItemsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetProjectItemsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetProjectItemsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetProjectItemsResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	if len(errors) > 0 {
		return GetProjectItemsResponseMultiError(errors)
	}

	return nil
}

// GetProjectItemsResponseMultiError is an error wrapping multiple validation
// errors returned by GetProjectItemsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetProjectItemsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProjectItemsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProjectItemsResponseMultiError) AllErrors() []error { return m }

// GetProjectItemsResponseValidationError is the validation error returned by
// GetProjectItemsResponse.Validate if the designated constraints aren't met.
type GetProjectItemsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectItemsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectItemsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectItemsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectItemsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectItemsResponseValidationError) ErrorName() string {
	return "GetProjectItemsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectItemsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectItemsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectItemsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectItemsResponseValidationError{}

// Validate checks the field values on GetGroupItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupItemsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupItemsRequestMultiError, or nil if none found.
func (m *GetGroupItemsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupItemsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	if len(errors) > 0 {
		return GetGroupItemsRequestMultiError(errors)
	}

	return nil
}

// GetGroupItemsRequestMultiError is an error wrapping multiple validation
// errors returned by GetGroupItemsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetGroupItemsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupItemsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupItemsRequestMultiError) AllErrors() []error { return m }

// GetGroupItemsRequestValidationError is the validation error returned by
// GetGroupItemsRequest.Validate if the designated constraints aren't met.
type GetGroupItemsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupItemsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupItemsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupItemsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupItemsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupItemsRequestValidationError) ErrorName() string {
	return "GetGroupItemsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupItemsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupItemsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupItemsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupItemsRequestValidationError{}

// Validate checks the field values on GetGroupItemsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupItemsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupItemsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupItemsResponseMultiError, or nil if none found.
func (m *GetGroupItemsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupItemsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetGroupItemsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetGroupItemsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetGroupItemsResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for GroupId

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	if len(errors) > 0 {
		return GetGroupItemsResponseMultiError(errors)
	}

	return nil
}

// GetGroupItemsResponseMultiError is an error wrapping multiple validation
// errors returned by GetGroupItemsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetGroupItemsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupItemsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupItemsResponseMultiError) AllErrors() []error { return m }

// GetGroupItemsResponseValidationError is the validation error returned by
// GetGroupItemsResponse.Validate if the designated constraints aren't met.
type GetGroupItemsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupItemsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupItemsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupItemsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupItemsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupItemsResponseValidationError) ErrorName() string {
	return "GetGroupItemsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupItemsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupItemsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupItemsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupItemsResponseValidationError{}

// Validate checks the field values on GetUserItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserItemsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserItemsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserItemsRequestMultiError, or nil if none found.
func (m *GetUserItemsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserItemsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	if len(errors) > 0 {
		return GetUserItemsRequestMultiError(errors)
	}

	return nil
}

// GetUserItemsRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserItemsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserItemsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserItemsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserItemsRequestMultiError) AllErrors() []error { return m }

// GetUserItemsRequestValidationError is the validation error returned by
// GetUserItemsRequest.Validate if the designated constraints aren't met.
type GetUserItemsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserItemsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserItemsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserItemsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserItemsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserItemsRequestValidationError) ErrorName() string {
	return "GetUserItemsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserItemsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserItemsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserItemsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserItemsRequestValidationError{}

// Validate checks the field values on GetUserItemsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserItemsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserItemsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserItemsResponseMultiError, or nil if none found.
func (m *GetUserItemsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserItemsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserItemsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserItemsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserItemsResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	if len(errors) > 0 {
		return GetUserItemsResponseMultiError(errors)
	}

	return nil
}

// GetUserItemsResponseMultiError is an error wrapping multiple validation
// errors returned by GetUserItemsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetUserItemsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserItemsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserItemsResponseMultiError) AllErrors() []error { return m }

// GetUserItemsResponseValidationError is the validation error returned by
// GetUserItemsResponse.Validate if the designated constraints aren't met.
type GetUserItemsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserItemsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserItemsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserItemsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserItemsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserItemsResponseValidationError) ErrorName() string {
	return "GetUserItemsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserItemsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserItemsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserItemsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserItemsResponseValidationError{}

// Validate checks the field values on GetItemRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetItemRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetItemRequestMultiError,
// or nil if none found.
func (m *GetItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for ItemId

	// no validation rules for UserId

	if len(errors) > 0 {
		return GetItemRequestMultiError(errors)
	}

	return nil
}

// GetItemRequestMultiError is an error wrapping multiple validation errors
// returned by GetItemRequest.ValidateAll() if the designated constraints
// aren't met.
type GetItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetItemRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetItemRequestMultiError) AllErrors() []error { return m }

// GetItemRequestValidationError is the validation error returned by
// GetItemRequest.Validate if the designated constraints aren't met.
type GetItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetItemRequestValidationError) ErrorName() string { return "GetItemRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetItemRequestValidationError{}

// Validate checks the field values on GetItemResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetItemResponseMultiError, or nil if none found.
func (m *GetItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetItemResponseValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetItemResponseValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetItemResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetItemResponseMultiError(errors)
	}

	return nil
}

// GetItemResponseMultiError is an error wrapping multiple validation errors
// returned by GetItemResponse.ValidateAll() if the designated constraints
// aren't met.
type GetItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetItemResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetItemResponseMultiError) AllErrors() []error { return m }

// GetItemResponseValidationError is the validation error returned by
// GetItemResponse.Validate if the designated constraints aren't met.
type GetItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetItemResponseValidationError) ErrorName() string { return "GetItemResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetItemResponseValidationError{}

// Validate checks the field values on CreateItemRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateItemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateItemRequestMultiError, or nil if none found.
func (m *CreateItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for Name

	// no validation rules for Atype

	// no validation rules for UserId

	if len(errors) > 0 {
		return CreateItemRequestMultiError(errors)
	}

	return nil
}

// CreateItemRequestMultiError is an error wrapping multiple validation errors
// returned by CreateItemRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateItemRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateItemRequestMultiError) AllErrors() []error { return m }

// CreateItemRequestValidationError is the validation error returned by
// CreateItemRequest.Validate if the designated constraints aren't met.
type CreateItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateItemRequestValidationError) ErrorName() string {
	return "CreateItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateItemRequestValidationError{}

// Validate checks the field values on CreateItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateItemResponseMultiError, or nil if none found.
func (m *CreateItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateItemResponseValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateItemResponseValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateItemResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateItemResponseMultiError(errors)
	}

	return nil
}

// CreateItemResponseMultiError is an error wrapping multiple validation errors
// returned by CreateItemResponse.ValidateAll() if the designated constraints
// aren't met.
type CreateItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateItemResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateItemResponseMultiError) AllErrors() []error { return m }

// CreateItemResponseValidationError is the validation error returned by
// CreateItemResponse.Validate if the designated constraints aren't met.
type CreateItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateItemResponseValidationError) ErrorName() string {
	return "CreateItemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateItemResponseValidationError{}

// Validate checks the field values on UpdateItemRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateItemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateItemRequestMultiError, or nil if none found.
func (m *UpdateItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for ItemId

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateItemRequestValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateItemRequestValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateItemRequestValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	if len(errors) > 0 {
		return UpdateItemRequestMultiError(errors)
	}

	return nil
}

// UpdateItemRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateItemRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateItemRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateItemRequestMultiError) AllErrors() []error { return m }

// UpdateItemRequestValidationError is the validation error returned by
// UpdateItemRequest.Validate if the designated constraints aren't met.
type UpdateItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateItemRequestValidationError) ErrorName() string {
	return "UpdateItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateItemRequestValidationError{}

// Validate checks the field values on UpdateItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateItemResponseMultiError, or nil if none found.
func (m *UpdateItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateItemResponseValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateItemResponseValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateItemResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateItemResponseMultiError(errors)
	}

	return nil
}

// UpdateItemResponseMultiError is an error wrapping multiple validation errors
// returned by UpdateItemResponse.ValidateAll() if the designated constraints
// aren't met.
type UpdateItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateItemResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateItemResponseMultiError) AllErrors() []error { return m }

// UpdateItemResponseValidationError is the validation error returned by
// UpdateItemResponse.Validate if the designated constraints aren't met.
type UpdateItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateItemResponseValidationError) ErrorName() string {
	return "UpdateItemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateItemResponseValidationError{}

// Validate checks the field values on DeleteItemRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteItemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteItemRequestMultiError, or nil if none found.
func (m *DeleteItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for ItemId

	// no validation rules for UserId

	if len(errors) > 0 {
		return DeleteItemRequestMultiError(errors)
	}

	return nil
}

// DeleteItemRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteItemRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteItemRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteItemRequestMultiError) AllErrors() []error { return m }

// DeleteItemRequestValidationError is the validation error returned by
// DeleteItemRequest.Validate if the designated constraints aren't met.
type DeleteItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteItemRequestValidationError) ErrorName() string {
	return "DeleteItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteItemRequestValidationError{}

// Validate checks the field values on DeleteItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteItemResponseMultiError, or nil if none found.
func (m *DeleteItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteItemResponseMultiError(errors)
	}

	return nil
}

// DeleteItemResponseMultiError is an error wrapping multiple validation errors
// returned by DeleteItemResponse.ValidateAll() if the designated constraints
// aren't met.
type DeleteItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteItemResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteItemResponseMultiError) AllErrors() []error { return m }

// DeleteItemResponseValidationError is the validation error returned by
// DeleteItemResponse.Validate if the designated constraints aren't met.
type DeleteItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteItemResponseValidationError) ErrorName() string {
	return "DeleteItemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteItemResponseValidationError{}

// Validate checks the field values on LikeItemRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LikeItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LikeItemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LikeItemRequestMultiError, or nil if none found.
func (m *LikeItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LikeItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for ItemId

	// no validation rules for UserId

	// no validation rules for Islike

	if len(errors) > 0 {
		return LikeItemRequestMultiError(errors)
	}

	return nil
}

// LikeItemRequestMultiError is an error wrapping multiple validation errors
// returned by LikeItemRequest.ValidateAll() if the designated constraints
// aren't met.
type LikeItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LikeItemRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LikeItemRequestMultiError) AllErrors() []error { return m }

// LikeItemRequestValidationError is the validation error returned by
// LikeItemRequest.Validate if the designated constraints aren't met.
type LikeItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LikeItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LikeItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LikeItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LikeItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LikeItemRequestValidationError) ErrorName() string { return "LikeItemRequestValidationError" }

// Error satisfies the builtin error interface
func (e LikeItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLikeItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LikeItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LikeItemRequestValidationError{}

// Validate checks the field values on LikeItemResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LikeItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LikeItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LikeItemResponseMultiError, or nil if none found.
func (m *LikeItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LikeItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return LikeItemResponseMultiError(errors)
	}

	return nil
}

// LikeItemResponseMultiError is an error wrapping multiple validation errors
// returned by LikeItemResponse.ValidateAll() if the designated constraints
// aren't met.
type LikeItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LikeItemResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LikeItemResponseMultiError) AllErrors() []error { return m }

// LikeItemResponseValidationError is the validation error returned by
// LikeItemResponse.Validate if the designated constraints aren't met.
type LikeItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LikeItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LikeItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LikeItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LikeItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LikeItemResponseValidationError) ErrorName() string { return "LikeItemResponseValidationError" }

// Error satisfies the builtin error interface
func (e LikeItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLikeItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LikeItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LikeItemResponseValidationError{}
