// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: github.com/grapery/grapery/common-protoc/project.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on GetProjectRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetProjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	return nil
}

// GetProjectRequestValidationError is the validation error returned by
// GetProjectRequest.Validate if the designated constraints aren't met.
type GetProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectRequestValidationError) ErrorName() string {
	return "GetProjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectRequestValidationError{}

// Validate checks the field values on GetProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetProjectResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetProjectResponseValidationError is the validation error returned by
// GetProjectResponse.Validate if the designated constraints aren't met.
type GetProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectResponseValidationError) ErrorName() string {
	return "GetProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectResponseValidationError{}

// Validate checks the field values on CreateProjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateProjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for Name

	return nil
}

// CreateProjectRequestValidationError is the validation error returned by
// CreateProjectRequest.Validate if the designated constraints aren't met.
type CreateProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProjectRequestValidationError) ErrorName() string {
	return "CreateProjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProjectRequestValidationError{}

// Validate checks the field values on CreateProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateProjectResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateProjectResponseValidationError is the validation error returned by
// CreateProjectResponse.Validate if the designated constraints aren't met.
type CreateProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProjectResponseValidationError) ErrorName() string {
	return "CreateProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProjectResponseValidationError{}

// Validate checks the field values on UpdateProjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateProjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateProjectRequestValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateProjectRequestValidationError is the validation error returned by
// UpdateProjectRequest.Validate if the designated constraints aren't met.
type UpdateProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProjectRequestValidationError) ErrorName() string {
	return "UpdateProjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProjectRequestValidationError{}

// Validate checks the field values on UpdateProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateProjectResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateProjectResponseValidationError is the validation error returned by
// UpdateProjectResponse.Validate if the designated constraints aren't met.
type UpdateProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProjectResponseValidationError) ErrorName() string {
	return "UpdateProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProjectResponseValidationError{}

// Validate checks the field values on DeleteProjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DeleteProjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	return nil
}

// DeleteProjectRequestValidationError is the validation error returned by
// DeleteProjectRequest.Validate if the designated constraints aren't met.
type DeleteProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteProjectRequestValidationError) ErrorName() string {
	return "DeleteProjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteProjectRequestValidationError{}

// Validate checks the field values on DeleteProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DeleteProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// DeleteProjectResponseValidationError is the validation error returned by
// DeleteProjectResponse.Validate if the designated constraints aren't met.
type DeleteProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteProjectResponseValidationError) ErrorName() string {
	return "DeleteProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteProjectResponseValidationError{}

// Validate checks the field values on GetProjectProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetProjectProfileRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	return nil
}

// GetProjectProfileRequestValidationError is the validation error returned by
// GetProjectProfileRequest.Validate if the designated constraints aren't met.
type GetProjectProfileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectProfileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectProfileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectProfileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectProfileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectProfileRequestValidationError) ErrorName() string {
	return "GetProjectProfileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectProfileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectProfileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectProfileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectProfileRequestValidationError{}

// Validate checks the field values on GetProjectProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetProjectProfileResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetProjectProfileResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetProjectProfileResponseValidationError is the validation error returned by
// GetProjectProfileResponse.Validate if the designated constraints aren't met.
type GetProjectProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectProfileResponseValidationError) ErrorName() string {
	return "GetProjectProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectProfileResponseValidationError{}

// Validate checks the field values on UpdateProjectProfileRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateProjectProfileRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateProjectProfileRequestValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateProjectProfileRequestValidationError is the validation error returned
// by UpdateProjectProfileRequest.Validate if the designated constraints
// aren't met.
type UpdateProjectProfileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProjectProfileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProjectProfileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProjectProfileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProjectProfileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProjectProfileRequestValidationError) ErrorName() string {
	return "UpdateProjectProfileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateProjectProfileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProjectProfileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProjectProfileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProjectProfileRequestValidationError{}

// Validate checks the field values on UpdateProjectProfileResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateProjectProfileResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateProjectProfileResponseValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateProjectProfileResponseValidationError is the validation error returned
// by UpdateProjectProfileResponse.Validate if the designated constraints
// aren't met.
type UpdateProjectProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProjectProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProjectProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProjectProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProjectProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProjectProfileResponseValidationError) ErrorName() string {
	return "UpdateProjectProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateProjectProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProjectProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProjectProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProjectProfileResponseValidationError{}

// Validate checks the field values on GetWatchingProjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetWatchingProjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// GetWatchingProjectRequestValidationError is the validation error returned by
// GetWatchingProjectRequest.Validate if the designated constraints aren't met.
type GetWatchingProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWatchingProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWatchingProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWatchingProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWatchingProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWatchingProjectRequestValidationError) ErrorName() string {
	return "GetWatchingProjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetWatchingProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWatchingProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWatchingProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWatchingProjectRequestValidationError{}

// Validate checks the field values on GetWatchingProjectResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetWatchingProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetWatchingProjectResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// GetWatchingProjectResponseValidationError is the validation error returned
// by GetWatchingProjectResponse.Validate if the designated constraints aren't met.
type GetWatchingProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWatchingProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWatchingProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWatchingProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWatchingProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWatchingProjectResponseValidationError) ErrorName() string {
	return "GetWatchingProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetWatchingProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWatchingProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWatchingProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWatchingProjectResponseValidationError{}

// Validate checks the field values on WatchProjectReqeust with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *WatchProjectReqeust) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	return nil
}

// WatchProjectReqeustValidationError is the validation error returned by
// WatchProjectReqeust.Validate if the designated constraints aren't met.
type WatchProjectReqeustValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchProjectReqeustValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchProjectReqeustValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchProjectReqeustValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchProjectReqeustValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchProjectReqeustValidationError) ErrorName() string {
	return "WatchProjectReqeustValidationError"
}

// Error satisfies the builtin error interface
func (e WatchProjectReqeustValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchProjectReqeust.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchProjectReqeustValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchProjectReqeustValidationError{}

// Validate checks the field values on WatchProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *WatchProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// WatchProjectResponseValidationError is the validation error returned by
// WatchProjectResponse.Validate if the designated constraints aren't met.
type WatchProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchProjectResponseValidationError) ErrorName() string {
	return "WatchProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e WatchProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchProjectResponseValidationError{}

// Validate checks the field values on UnWatchProjectReqeust with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UnWatchProjectReqeust) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	return nil
}

// UnWatchProjectReqeustValidationError is the validation error returned by
// UnWatchProjectReqeust.Validate if the designated constraints aren't met.
type UnWatchProjectReqeustValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnWatchProjectReqeustValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnWatchProjectReqeustValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnWatchProjectReqeustValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnWatchProjectReqeustValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnWatchProjectReqeustValidationError) ErrorName() string {
	return "UnWatchProjectReqeustValidationError"
}

// Error satisfies the builtin error interface
func (e UnWatchProjectReqeustValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnWatchProjectReqeust.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnWatchProjectReqeustValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnWatchProjectReqeustValidationError{}

// Validate checks the field values on UnWatchProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UnWatchProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// UnWatchProjectResponseValidationError is the validation error returned by
// UnWatchProjectResponse.Validate if the designated constraints aren't met.
type UnWatchProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnWatchProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnWatchProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnWatchProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnWatchProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnWatchProjectResponseValidationError) ErrorName() string {
	return "UnWatchProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UnWatchProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnWatchProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnWatchProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnWatchProjectResponseValidationError{}

// Validate checks the field values on ExploreProjectsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ExploreProjectsRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// ExploreProjectsRequestValidationError is the validation error returned by
// ExploreProjectsRequest.Validate if the designated constraints aren't met.
type ExploreProjectsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExploreProjectsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExploreProjectsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExploreProjectsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExploreProjectsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExploreProjectsRequestValidationError) ErrorName() string {
	return "ExploreProjectsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExploreProjectsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExploreProjectsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExploreProjectsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExploreProjectsRequestValidationError{}

// Validate checks the field values on ExploreProjectsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ExploreProjectsResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExploreProjectsResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// ExploreProjectsResponseValidationError is the validation error returned by
// ExploreProjectsResponse.Validate if the designated constraints aren't met.
type ExploreProjectsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExploreProjectsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExploreProjectsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExploreProjectsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExploreProjectsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExploreProjectsResponseValidationError) ErrorName() string {
	return "ExploreProjectsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ExploreProjectsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExploreProjectsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExploreProjectsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExploreProjectsResponseValidationError{}

// Validate checks the field values on SearchProjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SearchProjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for Name

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// SearchProjectRequestValidationError is the validation error returned by
// SearchProjectRequest.Validate if the designated constraints aren't met.
type SearchProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchProjectRequestValidationError) ErrorName() string {
	return "SearchProjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchProjectRequestValidationError{}

// Validate checks the field values on SearchProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SearchProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchProjectResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// SearchProjectResponseValidationError is the validation error returned by
// SearchProjectResponse.Validate if the designated constraints aren't met.
type SearchProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchProjectResponseValidationError) ErrorName() string {
	return "SearchProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchProjectResponseValidationError{}

// Validate checks the field values on SearchAllProjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SearchAllProjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for Name

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// SearchAllProjectRequestValidationError is the validation error returned by
// SearchAllProjectRequest.Validate if the designated constraints aren't met.
type SearchAllProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchAllProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchAllProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchAllProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchAllProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchAllProjectRequestValidationError) ErrorName() string {
	return "SearchAllProjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchAllProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchAllProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchAllProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchAllProjectRequestValidationError{}

// Validate checks the field values on SearchAllProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SearchAllProjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchAllProjectResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Offset

	// no validation rules for Number

	return nil
}

// SearchAllProjectResponseValidationError is the validation error returned by
// SearchAllProjectResponse.Validate if the designated constraints aren't met.
type SearchAllProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchAllProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchAllProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchAllProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchAllProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchAllProjectResponseValidationError) ErrorName() string {
	return "SearchAllProjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchAllProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchAllProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchAllProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchAllProjectResponseValidationError{}
