// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: github.com/grapery/grapery/common-protoc/service.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on VersionRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VersionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VersionRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VersionRequestMultiError,
// or nil if none found.
func (m *VersionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *VersionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return VersionRequestMultiError(errors)
	}

	return nil
}

// VersionRequestMultiError is an error wrapping multiple validation errors
// returned by VersionRequest.ValidateAll() if the designated constraints
// aren't met.
type VersionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VersionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VersionRequestMultiError) AllErrors() []error { return m }

// VersionRequestValidationError is the validation error returned by
// VersionRequest.Validate if the designated constraints aren't met.
type VersionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VersionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VersionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VersionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VersionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VersionRequestValidationError) ErrorName() string { return "VersionRequestValidationError" }

// Error satisfies the builtin error interface
func (e VersionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVersionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VersionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VersionRequestValidationError{}

// Validate checks the field values on VersionResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VersionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VersionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VersionResponseMultiError, or nil if none found.
func (m *VersionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *VersionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Version

	if len(errors) > 0 {
		return VersionResponseMultiError(errors)
	}

	return nil
}

// VersionResponseMultiError is an error wrapping multiple validation errors
// returned by VersionResponse.ValidateAll() if the designated constraints
// aren't met.
type VersionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VersionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VersionResponseMultiError) AllErrors() []error { return m }

// VersionResponseValidationError is the validation error returned by
// VersionResponse.Validate if the designated constraints aren't met.
type VersionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VersionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VersionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VersionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VersionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VersionResponseValidationError) ErrorName() string { return "VersionResponseValidationError" }

// Error satisfies the builtin error interface
func (e VersionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVersionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VersionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VersionResponseValidationError{}

// Validate checks the field values on AboutRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AboutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AboutRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AboutRequestMultiError, or
// nil if none found.
func (m *AboutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AboutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AboutRequestMultiError(errors)
	}

	return nil
}

// AboutRequestMultiError is an error wrapping multiple validation errors
// returned by AboutRequest.ValidateAll() if the designated constraints aren't met.
type AboutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AboutRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AboutRequestMultiError) AllErrors() []error { return m }

// AboutRequestValidationError is the validation error returned by
// AboutRequest.Validate if the designated constraints aren't met.
type AboutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AboutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AboutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AboutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AboutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AboutRequestValidationError) ErrorName() string { return "AboutRequestValidationError" }

// Error satisfies the builtin error interface
func (e AboutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAboutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AboutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AboutRequestValidationError{}

// Validate checks the field values on AboutResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AboutResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AboutResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AboutResponseMultiError, or
// nil if none found.
func (m *AboutResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AboutResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Content

	if len(errors) > 0 {
		return AboutResponseMultiError(errors)
	}

	return nil
}

// AboutResponseMultiError is an error wrapping multiple validation errors
// returned by AboutResponse.ValidateAll() if the designated constraints
// aren't met.
type AboutResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AboutResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AboutResponseMultiError) AllErrors() []error { return m }

// AboutResponseValidationError is the validation error returned by
// AboutResponse.Validate if the designated constraints aren't met.
type AboutResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AboutResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AboutResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AboutResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AboutResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AboutResponseValidationError) ErrorName() string { return "AboutResponseValidationError" }

// Error satisfies the builtin error interface
func (e AboutResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAboutResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AboutResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AboutResponseValidationError{}

// Validate checks the field values on ExploreRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExploreRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExploreRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExploreRequestMultiError,
// or nil if none found.
func (m *ExploreRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExploreRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ExploreRequestMultiError(errors)
	}

	return nil
}

// ExploreRequestMultiError is an error wrapping multiple validation errors
// returned by ExploreRequest.ValidateAll() if the designated constraints
// aren't met.
type ExploreRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExploreRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExploreRequestMultiError) AllErrors() []error { return m }

// ExploreRequestValidationError is the validation error returned by
// ExploreRequest.Validate if the designated constraints aren't met.
type ExploreRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExploreRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExploreRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExploreRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExploreRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExploreRequestValidationError) ErrorName() string { return "ExploreRequestValidationError" }

// Error satisfies the builtin error interface
func (e ExploreRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExploreRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExploreRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExploreRequestValidationError{}

// Validate checks the field values on ExploreResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ExploreResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExploreResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExploreResponseMultiError, or nil if none found.
func (m *ExploreResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ExploreResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ExploreResponseMultiError(errors)
	}

	return nil
}

// ExploreResponseMultiError is an error wrapping multiple validation errors
// returned by ExploreResponse.ValidateAll() if the designated constraints
// aren't met.
type ExploreResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExploreResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExploreResponseMultiError) AllErrors() []error { return m }

// ExploreResponseValidationError is the validation error returned by
// ExploreResponse.Validate if the designated constraints aren't met.
type ExploreResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExploreResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExploreResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExploreResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExploreResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExploreResponseValidationError) ErrorName() string { return "ExploreResponseValidationError" }

// Error satisfies the builtin error interface
func (e ExploreResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExploreResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExploreResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExploreResponseValidationError{}

// Validate checks the field values on TrendingRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TrendingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrendingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrendingRequestMultiError, or nil if none found.
func (m *TrendingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TrendingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TrendingRequestMultiError(errors)
	}

	return nil
}

// TrendingRequestMultiError is an error wrapping multiple validation errors
// returned by TrendingRequest.ValidateAll() if the designated constraints
// aren't met.
type TrendingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrendingRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrendingRequestMultiError) AllErrors() []error { return m }

// TrendingRequestValidationError is the validation error returned by
// TrendingRequest.Validate if the designated constraints aren't met.
type TrendingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrendingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrendingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrendingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrendingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrendingRequestValidationError) ErrorName() string { return "TrendingRequestValidationError" }

// Error satisfies the builtin error interface
func (e TrendingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrendingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrendingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrendingRequestValidationError{}

// Validate checks the field values on TrendingResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TrendingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrendingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrendingResponseMultiError, or nil if none found.
func (m *TrendingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TrendingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TrendingResponseMultiError(errors)
	}

	return nil
}

// TrendingResponseMultiError is an error wrapping multiple validation errors
// returned by TrendingResponse.ValidateAll() if the designated constraints
// aren't met.
type TrendingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrendingResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrendingResponseMultiError) AllErrors() []error { return m }

// TrendingResponseValidationError is the validation error returned by
// TrendingResponse.Validate if the designated constraints aren't met.
type TrendingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrendingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrendingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrendingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrendingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrendingResponseValidationError) ErrorName() string { return "TrendingResponseValidationError" }

// Error satisfies the builtin error interface
func (e TrendingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrendingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrendingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrendingResponseValidationError{}
