// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: github.com/grapery/grapery/common-protoc/team.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetGroupTeamsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID int64 `protobuf:"varint,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	UserID  int64 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Offset  int64 `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit   int64 `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *GetGroupTeamsReq) Reset() {
	*x = GetGroupTeamsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupTeamsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupTeamsReq) ProtoMessage() {}

func (x *GetGroupTeamsReq) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupTeamsReq.ProtoReflect.Descriptor instead.
func (*GetGroupTeamsReq) Descriptor() ([]byte, []int) {
	return file_github_com_grapery_grapery_common_protoc_team_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupTeamsReq) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *GetGroupTeamsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetGroupTeamsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGroupTeamsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGroupTeamsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID int64       `protobuf:"varint,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	UserID  int64       `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	List    []*TeamInfo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	Offset  int64       `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit   int64       `protobuf:"varint,5,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *GetGroupTeamsResp) Reset() {
	*x = GetGroupTeamsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupTeamsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupTeamsResp) ProtoMessage() {}

func (x *GetGroupTeamsResp) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupTeamsResp.ProtoReflect.Descriptor instead.
func (*GetGroupTeamsResp) Descriptor() ([]byte, []int) {
	return file_github_com_grapery_grapery_common_protoc_team_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupTeamsResp) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *GetGroupTeamsResp) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetGroupTeamsResp) GetList() []*TeamInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetGroupTeamsResp) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGroupTeamsResp) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateGroupTeamsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID int64  `protobuf:"varint,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	UserID  int64  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateGroupTeamsReq) Reset() {
	*x = CreateGroupTeamsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupTeamsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupTeamsReq) ProtoMessage() {}

func (x *CreateGroupTeamsReq) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupTeamsReq.ProtoReflect.Descriptor instead.
func (*CreateGroupTeamsReq) Descriptor() ([]byte, []int) {
	return file_github_com_grapery_grapery_common_protoc_team_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupTeamsReq) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *CreateGroupTeamsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateGroupTeamsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateGroupTeamsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID int64     `protobuf:"varint,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	UserID  int64     `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Info    *TeamInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *CreateGroupTeamsResp) Reset() {
	*x = CreateGroupTeamsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupTeamsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupTeamsResp) ProtoMessage() {}

func (x *CreateGroupTeamsResp) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupTeamsResp.ProtoReflect.Descriptor instead.
func (*CreateGroupTeamsResp) Descriptor() ([]byte, []int) {
	return file_github_com_grapery_grapery_common_protoc_team_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupTeamsResp) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *CreateGroupTeamsResp) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateGroupTeamsResp) GetInfo() *TeamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_github_com_grapery_grapery_common_protoc_team_proto protoreflect.FileDescriptor

var file_github_com_grapery_grapery_common_protoc_team_proto_rawDesc = []byte{
	0x0a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x61,
	0x70, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x61, 0x70, 0x65, 0x72, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x61, 0x70,
	0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x9e,
	0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65, 0x61, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x65, 0x72, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x5b, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x73, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65, 0x61, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x65, 0x72, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x72, 0x61, 0x70, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x72, 0x79, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_grapery_grapery_common_protoc_team_proto_rawDescOnce sync.Once
	file_github_com_grapery_grapery_common_protoc_team_proto_rawDescData = file_github_com_grapery_grapery_common_protoc_team_proto_rawDesc
)

func file_github_com_grapery_grapery_common_protoc_team_proto_rawDescGZIP() []byte {
	file_github_com_grapery_grapery_common_protoc_team_proto_rawDescOnce.Do(func() {
		file_github_com_grapery_grapery_common_protoc_team_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_grapery_grapery_common_protoc_team_proto_rawDescData)
	})
	return file_github_com_grapery_grapery_common_protoc_team_proto_rawDescData
}

var file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_grapery_grapery_common_protoc_team_proto_goTypes = []interface{}{
	(*GetGroupTeamsReq)(nil),     // 0: grapery.api.GetGroupTeamsReq
	(*GetGroupTeamsResp)(nil),    // 1: grapery.api.GetGroupTeamsResp
	(*CreateGroupTeamsReq)(nil),  // 2: grapery.api.CreateGroupTeamsReq
	(*CreateGroupTeamsResp)(nil), // 3: grapery.api.CreateGroupTeamsResp
	(*TeamInfo)(nil),             // 4: grapery.api.TeamInfo
}
var file_github_com_grapery_grapery_common_protoc_team_proto_depIdxs = []int32{
	4, // 0: grapery.api.GetGroupTeamsResp.list:type_name -> grapery.api.TeamInfo
	4, // 1: grapery.api.CreateGroupTeamsResp.info:type_name -> grapery.api.TeamInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_grapery_grapery_common_protoc_team_proto_init() }
func file_github_com_grapery_grapery_common_protoc_team_proto_init() {
	if File_github_com_grapery_grapery_common_protoc_team_proto != nil {
		return
	}
	file_github_com_grapery_grapery_common_protoc_view_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupTeamsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupTeamsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupTeamsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupTeamsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_grapery_grapery_common_protoc_team_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_grapery_grapery_common_protoc_team_proto_goTypes,
		DependencyIndexes: file_github_com_grapery_grapery_common_protoc_team_proto_depIdxs,
		MessageInfos:      file_github_com_grapery_grapery_common_protoc_team_proto_msgTypes,
	}.Build()
	File_github_com_grapery_grapery_common_protoc_team_proto = out.File
	file_github_com_grapery_grapery_common_protoc_team_proto_rawDesc = nil
	file_github_com_grapery_grapery_common_protoc_team_proto_goTypes = nil
	file_github_com_grapery_grapery_common_protoc_team_proto_depIdxs = nil
}
