// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: github.com/grapery/grapery/common-protoc/view_model.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Tags with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Tags) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for CreatorID

	// no validation rules for Name

	return nil
}

// TagsValidationError is the validation error returned by Tags.Validate if the
// designated constraints aren't met.
type TagsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagsValidationError) ErrorName() string { return "TagsValidationError" }

// Error satisfies the builtin error interface
func (e TagsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTags.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagsValidationError{}

// Validate checks the field values on UserInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for Name

	// no validation rules for Avatar

	// no validation rules for Email

	// no validation rules for Location

	// no validation rules for Desc

	return nil
}

// UserInfoValidationError is the validation error returned by
// UserInfo.Validate if the designated constraints aren't met.
type UserInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserInfoValidationError) ErrorName() string { return "UserInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserInfoValidationError{}

// Validate checks the field values on GroupInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *GroupInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for Name

	// no validation rules for Avatar

	// no validation rules for Desc

	if v, ok := interface{}(m.GetCreator()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GroupInfoValidationError{
				field:  "Creator",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetOwner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GroupInfoValidationError{
				field:  "Owner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetTags() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GroupInfoValidationError{
					field:  fmt.Sprintf("Tags[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// GroupInfoValidationError is the validation error returned by
// GroupInfo.Validate if the designated constraints aren't met.
type GroupInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupInfoValidationError) ErrorName() string { return "GroupInfoValidationError" }

// Error satisfies the builtin error interface
func (e GroupInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupInfoValidationError{}

// Validate checks the field values on ProjectInfo with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ProjectInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ProjectId

	// no validation rules for GroupId

	// no validation rules for Name

	// no validation rules for Avatar

	if v, ok := interface{}(m.GetCreator()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProjectInfoValidationError{
				field:  "Creator",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetOwner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProjectInfoValidationError{
				field:  "Owner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetTags() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectInfoValidationError{
					field:  fmt.Sprintf("Tags[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Visable

	// no validation rules for IsAchieve

	// no validation rules for IsClose

	return nil
}

// ProjectInfoValidationError is the validation error returned by
// ProjectInfo.Validate if the designated constraints aren't met.
type ProjectInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectInfoValidationError) ErrorName() string { return "ProjectInfoValidationError" }

// Error satisfies the builtin error interface
func (e ProjectInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectInfoValidationError{}

// Validate checks the field values on ProjectProfileInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ProjectProfileInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ProjectId

	// no validation rules for GroupId

	// no validation rules for Description

	// no validation rules for WatchingCount

	// no validation rules for InvolvedCount

	// no validation rules for Avatar

	// no validation rules for Visable

	// no validation rules for IsAchieve

	// no validation rules for IsClose

	// no validation rules for IsPrivate

	return nil
}

// ProjectProfileInfoValidationError is the validation error returned by
// ProjectProfileInfo.Validate if the designated constraints aren't met.
type ProjectProfileInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectProfileInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectProfileInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectProfileInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectProfileInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectProfileInfoValidationError) ErrorName() string {
	return "ProjectProfileInfoValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectProfileInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectProfileInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectProfileInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectProfileInfoValidationError{}

// Validate checks the field values on ActiveInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ActiveInfo) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ActiveInfoValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ActiveType

	if v, ok := interface{}(m.GetItemInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ActiveInfoValidationError{
				field:  "ItemInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetProjectInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ActiveInfoValidationError{
				field:  "ProjectInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetGroupInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ActiveInfoValidationError{
				field:  "GroupInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ActiveInfoValidationError is the validation error returned by
// ActiveInfo.Validate if the designated constraints aren't met.
type ActiveInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ActiveInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ActiveInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ActiveInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ActiveInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ActiveInfoValidationError) ErrorName() string { return "ActiveInfoValidationError" }

// Error satisfies the builtin error interface
func (e ActiveInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sActiveInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ActiveInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ActiveInfoValidationError{}

// Validate checks the field values on WordDetail with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *WordDetail) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// WordDetailValidationError is the validation error returned by
// WordDetail.Validate if the designated constraints aren't met.
type WordDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WordDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WordDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WordDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WordDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WordDetailValidationError) ErrorName() string { return "WordDetailValidationError" }

// Error satisfies the builtin error interface
func (e WordDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWordDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WordDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WordDetailValidationError{}

// Validate checks the field values on PictureDetail with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PictureDetail) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// PictureDetailValidationError is the validation error returned by
// PictureDetail.Validate if the designated constraints aren't met.
type PictureDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PictureDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PictureDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PictureDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PictureDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PictureDetailValidationError) ErrorName() string { return "PictureDetailValidationError" }

// Error satisfies the builtin error interface
func (e PictureDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPictureDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PictureDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PictureDetailValidationError{}

// Validate checks the field values on VideoDetail with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *VideoDetail) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// VideoDetailValidationError is the validation error returned by
// VideoDetail.Validate if the designated constraints aren't met.
type VideoDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VideoDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VideoDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VideoDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VideoDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VideoDetailValidationError) ErrorName() string { return "VideoDetailValidationError" }

// Error satisfies the builtin error interface
func (e VideoDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVideoDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VideoDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VideoDetailValidationError{}

// Validate checks the field values on MusicDetail with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MusicDetail) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// MusicDetailValidationError is the validation error returned by
// MusicDetail.Validate if the designated constraints aren't met.
type MusicDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MusicDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MusicDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MusicDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MusicDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MusicDetailValidationError) ErrorName() string { return "MusicDetailValidationError" }

// Error satisfies the builtin error interface
func (e MusicDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMusicDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MusicDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MusicDetailValidationError{}

// Validate checks the field values on VoiceDetail with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *VoiceDetail) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// VoiceDetailValidationError is the validation error returned by
// VoiceDetail.Validate if the designated constraints aren't met.
type VoiceDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VoiceDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VoiceDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VoiceDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VoiceDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VoiceDetailValidationError) ErrorName() string { return "VoiceDetailValidationError" }

// Error satisfies the builtin error interface
func (e VoiceDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVoiceDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VoiceDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VoiceDetailValidationError{}

// Validate checks the field values on ShareDetail with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ShareDetail) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ShareDetailValidationError is the validation error returned by
// ShareDetail.Validate if the designated constraints aren't met.
type ShareDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShareDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShareDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShareDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShareDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShareDetailValidationError) ErrorName() string { return "ShareDetailValidationError" }

// Error satisfies the builtin error interface
func (e ShareDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShareDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShareDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShareDetailValidationError{}

// Validate checks the field values on ItemDetail with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ItemDetail) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Detail.(type) {

	case *ItemDetail_Word:

		if v, ok := interface{}(m.GetWord()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemDetailValidationError{
					field:  "Word",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ItemDetail_Pictures:

		if v, ok := interface{}(m.GetPictures()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemDetailValidationError{
					field:  "Pictures",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ItemDetail_Video:

		if v, ok := interface{}(m.GetVideo()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemDetailValidationError{
					field:  "Video",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ItemDetail_Music:

		if v, ok := interface{}(m.GetMusic()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemDetailValidationError{
					field:  "Music",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ItemDetail_Voice:

		if v, ok := interface{}(m.GetVoice()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemDetailValidationError{
					field:  "Voice",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ItemDetail_Share:

		if v, ok := interface{}(m.GetShare()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemDetailValidationError{
					field:  "Share",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ItemDetailValidationError is the validation error returned by
// ItemDetail.Validate if the designated constraints aren't met.
type ItemDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ItemDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ItemDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ItemDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ItemDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ItemDetailValidationError) ErrorName() string { return "ItemDetailValidationError" }

// Error satisfies the builtin error interface
func (e ItemDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sItemDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ItemDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ItemDetailValidationError{}

// Validate checks the field values on ItemInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ItemInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for GroupId

	// no validation rules for ProjectId

	// no validation rules for UserId

	// no validation rules for Title

	if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ItemInfoValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Itype

	return nil
}

// ItemInfoValidationError is the validation error returned by
// ItemInfo.Validate if the designated constraints aren't met.
type ItemInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ItemInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ItemInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ItemInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ItemInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ItemInfoValidationError) ErrorName() string { return "ItemInfoValidationError" }

// Error satisfies the builtin error interface
func (e ItemInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sItemInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ItemInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ItemInfoValidationError{}

// Validate checks the field values on UserProfileInfo with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *UserProfileInfo) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// UserProfileInfoValidationError is the validation error returned by
// UserProfileInfo.Validate if the designated constraints aren't met.
type UserProfileInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserProfileInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserProfileInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserProfileInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserProfileInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserProfileInfoValidationError) ErrorName() string { return "UserProfileInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserProfileInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserProfileInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserProfileInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserProfileInfoValidationError{}

// Validate checks the field values on GroupProfileInfo with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GroupProfileInfo) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GroupProfileInfoValidationError is the validation error returned by
// GroupProfileInfo.Validate if the designated constraints aren't met.
type GroupProfileInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupProfileInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupProfileInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupProfileInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupProfileInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupProfileInfoValidationError) ErrorName() string { return "GroupProfileInfoValidationError" }

// Error satisfies the builtin error interface
func (e GroupProfileInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupProfileInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupProfileInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupProfileInfoValidationError{}
